- utils/ssh/sshcmd.go
there are many diffrent situations when we run command remotely. so we need to print "SSH.cmd" output to make log meassage more readable .
printf output of this function:  session.CombinedOutput(cmd)
> refactor:print ssh cmd output when exec failed

- runtime/masters.go
more master 
```
2021-05-20 17:49:05 [INFO] [ssh][192.168.64.12] : grep -qF "apiserver.cluster.local" /etc/kubernetes/scheduler.conf  && sed -i 's/apiserver.cluster.local/192.168.64.12/' /etc/kubernetes/controller-manager.conf && sed -i 's/apiserver.cluster.local/192.168.64.12/' /etc/kubernetes/scheduler.conf
grep: /etc/kubernetes/scheduler.conf: No such file or directory
2021-05-20 17:49:05 [EROR] exec command failed Process exited with status 2
```
> fix(main): more master replace error

- build/build.go
- build/cloud_builder.go
- build/local_builder.go
- build/testing/cloud_builder_test.go
- build/testing/local_builder_test.go
- sealer/cmd/build.go
- seautil/cmd/build.go
support to add clusterfile to all image whatever build type is
Fixes  #107
local build : find cluster file from kubefile, image matadata,rootfs .
cloud build : first find clusterfile from its applied, if not exist ,find it from local build steps.
if base image  is scratch, then read clusterfile from etc/Clusterfile
run local build: sealer build -f Kubefile -t {your image name } -b local .
run cloud build :  sealer build -f Kubefile -t {your image name } .
run build rootfs : from  scratch
> bugfix:add clusterfile to all image whatever build type is

- utils/compress/compress.go
hash of tar contains many header info, so hash will change in different machine, so I hardcode the gname and uname for the file header to avoid this problem.
Fixes #151 
this is just a temp solution. A better layer arch is more needed.
> fix hash of tar diff

- runtime/kubeadm.go
- runtime/template.go
fix duplicated certSANS in generated kubeadm config file
Fixes #220 
Using `utils.AppendIPList` to append all IP address into a single slice for `CertSANS` of env map, 
so we can prevent duplicated IP.
> fix: duplicated certSANS in generated kubeadm config file

- docs/user-guide/get-started.md
when we add masters or nodes, we should execute the shell script 'sealer join --masters 192.168.0.2 --nodes 192.168.0.3'
> fixed 'sealer join' command description

- runtime/init.go
- types/api/v1/cluster_types.go
```
apiVersion: zlink.aliyun.com/v1alpha1
kind: Cluster
metadata:
spec:
certSANS:
- aliyun-inc.com
- 10.0.0.2
image: kubernetes:v1.19.9
masters:
count: "1"
cpu: "4"
dataDisks:
- "100"
memory: "4"
systemDisk: "100"
network:
cniName: calico
interface: eth0
ipip: true
podCIDR: 100.64.0.0/10
svcCIDR: 10.96.0.0/22
provider: ALI_CLOUD
```
ipip: true will open IPIP
> add calico ipip config

- filesystem/filesystem.go
You should use: cluster.name instead of cluster.clustername, which results in a registry replication error
> fix clustername the problem of reference variable error

- apply/run.go
- guest/guest.go
1. use auto detect network interface name by master ip, when no network interface is set using the sealer run #385
2. fix the execution directory is incorrect
fix #387
> fix the execution directory is incorrect

- build/local_builder.go
- filesystem/filesystem.go
- utils/file.go
- utils/fswriters.go
Fix incorrectly copying dir path during build  fix #436 
Fixed invalid cross-device link error when executing AtomicWrite on different file partitioning systems.  #434
> Fix incorrectly copying dir path during build

- runtime/masters.go
remove unuse const RemoteRestartDocker
https://github.com/alibaba/sealer/blob/main/runtime/masters.go#L44
> refactor: remove unuse const RemoteRestartDocker

- utils/archive/compress.go
- utils/archive/compress_test.go
- utils/archive/const.go
- utils/file.go
- utils/system.go
we need to capable of serialize overlays files and opaque directory into tar stream, and deserialize them from tar stream.
such kind of processing tar stream is used at overlay upperdir majorly. 
* at tar stage, if we found that the current object is a whiteout(fi.Mode()&os.ModeCharDevice != 0 && header.Devminor == 0 && header.Devmajor == 0), we will add ".wh." as prefix to its header name, and set its size as 0, to make sure we won't read its content, which avoid whiteout read fault.
* at tar stage, if we found that the current object if opaque dir, dir with "trusted.overlay.opaque:y" attribute. we will set its header name as filepath.Join(header.Name, WhiteoutOpaqueDir)
when we untar them, will do corresponding jobs to recover original upper context.
> fix: support tar overlay files

- runtime/init.go
- runtime/kubeadm.go
- runtime/masters.go
- runtime/nodes.go
- runtime/runtime.go
- runtime/template.go
Signed-off-by: oldthreefeng <louisehong4168@gmail.com>
if we dont check node cgroupdriver and don't specific cgroup driver.  kubeadm will set it by default value.
Fixes #489 
use shell to get .
> feature: Use shell to check node cgroup driver before kubeadm init and join

- .golangci.yml
- apply/default_applier.go
- image/cache/chain.go
- image/distributionutil/pull.go
- image/distributionutil/push.go
- logger/conn.go
- logger/console.go
- runtime/init.go
- runtime/reset.go
- runtime/runtime.go
- utils/archive/compress.go
- utils/ssh/scp.go
- utils/ssh/sshcmd.go
When I apply golangci-lint with unparam rule, it throws the following error:
```
logger/conn.go:145:30: `(*connLogger).println` - `when` is unused (unparam)
func (c *connLogger) println(when time.Time, msg *loginfo) error {
^
logger/console.go:99:41: `(*consoleLogger).printlnToStdOut` - `when` is unused (unparam)
func (c *consoleLogger) printlnToStdOut(when time.Time, msg string) {
^
logger/console.go:105:41: `(*consoleLogger).printlnToStdErr` - `when` is unused (unparam)
func (c *consoleLogger) printlnToStdErr(when time.Time, msg string) {
^
utils/archive/compress.go:136:83: writeWhiteout - result 1 (error) is always nil (unparam)
func writeWhiteout(header *tar.Header, fi os.FileInfo, path string) (*tar.Header, error) {
^ …
```
> optimize: add unparam golangci-lint rule to remove unused parameters

- apply/run.go
- build/cloud_builder.go
- build/lite_builder.go
- build/utils.go
- image/default_image.go
- image/util.go
- sealer/cmd/inspect.go
I am afraid that there are several places misusing `returned parameters` and `log printing`. For example:
```
if err != nil {
logger.Error("failed to init image store, err: %s", err)
return ""
}
```
In this case, we used logger printing an detailed error, and just returned an empty to upper caller. Actually, upper caller is not aware of whether the function calling is successful. In general, we usually use a returned error to tell upper caller whether it works. So with the code above, there are two side effects:
* the upper caller must analyze the only returned string, to exact more information to decide what to do next. More implicit thing may occur;
* the sealer tool end user must see the detailed log to see what happened rather …
> refactor: remove error log and use return to transfer information

- build/lite/charts/charts_test.go
When I use codecov to detect the unit test cases of sealer, I found that lots of useless and un-validated test cases are there. As result, they are redundant and bring much effort to maintain. 
```
ok  	github.com/alibaba/sealer/build/lite	0.010s	coverage: 88.9% of statements
--- FAIL: TestDefaultChartsRootDir (0.00s)
--- FAIL: TestDefaultChartsRootDir/test_default_charts_root_directory (0.00s)
charts_test.go:46: defaultChartsRootDir() got = /var/lib/sealer/data/my_cluster/mount/charts, want /var/lib/sealer/data/my_cluster/rootfs/charts
--- FAIL: TestDefaultChartsRootDir/test_default_charts_root_directory_2 (0.00s)
charts_test.go:46: defaultChartsRootDir() got = /var/lib/sealer/data/second_cluster/mount/charts, want …
```
> test: fix an incorrect unit test case

- apply/cloud_applier.go
- apply/current_cluster.go
- apply/current_cluster_test.go
- apply/default_applier.go
- build/local_builder.go
- build/utils.go
- check/checker/node_checker.go
- check/checker/pod_checker.go
- check/checker/svc_checker.go
- check/service/post_check.go
- client/client.go
- plugin/labels.go
1. wrap `*kubernetes.Clientset` of k8s.io/client-go/kubernetes , and construct a new object K8sClient in package client
2. make every object who need to call k8s apiserver carry an instance of K8sClient
This could make the code more object-oriented. And encapsulate all the implementation just in the closure scope the defined struct.
none
none
none
none
> refactor: move k8s client detailed calling into an encapsulated obeject

- apply/default_applier.go
- build/local_builder.go
- build/utils.go
- check/checker/node_checker.go
- check/checker/pod_checker.go
- check/checker/svc_checker.go
- client/docker/container.go
- client/docker/docker_client.go
- client/docker/images.go
- client/k8s/client.go
- infra/container/container_image.go
- infra/container/provider_client.go
- plugin/labels.go
as we see, sealer will use many client such as k8s client and docker client. so i move it to its own dir with the name. 
- 1, move k8s client 
- 2, move docker client
> chore:remove docker client and k8s client to its dir

- runtime/template.go
When the sealer machine and the k8s-master0 machine are not the same machine
The custom tmpl file in the sealer machine is only in the mount folder, not in the rootfs folder
fixes #816 
Modified to read custom tmpl files from the mount folder
Recompile and execute again， it works;
> fix tmpl file definitely exists mount dir rather than rootfs dir

- apply/run.go
fix node parameter error in Clusterfile generated by apply the run command when node is empty
> fix node parameter error in Clusterfile generated by apply the run command when node is empty

- pkg/runtime/kubeadm_runtime.go
rootfs does not exist on the executing machine when the executing machine is not in the cluster node.
> fix the default kubeadm configuration from the mount image directory

- build/build.go
- build/buildkit/buildimage/build_image.go
- build/buildkit/buildimage/config.go
- build/buildkit/buildimage/image_interface.go
- build/buildkit/buildimage/utils.go
- build/buildkit/buildlayer/layerutils/charts/helm.go
- build/cloud/cloud_builder.go
- build/config.go
- build/lite/lite_builder.go
- build/local/local_builder.go
- common/common.go
- go.mod
- pkg/runtime/runtime.go
- pkg/runtime/utils.go
- sealer/cmd/build.go
- utils/file.go
- vendor/modules.txt
Applications Image contains applications with all dependencies except the base image, so ApplicationsImage can install to an already existing Kubernetes cluster.
add "--no-base" option for sealer build, if it is true, will only keep the application context and its docker image.
in order to keep the same with the "--no-cache" option. name it as "--no-base".
run this cmd will build app image:`sealer build -f Kubefile -t myapp:v1 -m lite . --no-base`
if want keep all images include base image, run `sealer build -f Kubefile -t myimage:v1 -m lite .`
link to issue #695
> feature: add without base option for sealer build

- applications/longhorn/Kubefile
- applications/longhorn/README.md
- applications/longhorn/longhorn.yaml
**what**
​	This PR is a longhorn image witch can provide a serries storage method.
**why**
​	Longhorn can provide a lightweight, reliable and easy-to-use distributed block storage system for Kubernetes.
Add support for longhorn. ( issuecomment-986387008)
#607
1. run a sealer kubernetes:v1.19.9 images cluster.
2. Install longhorn in the cluster by using helm.
3. Get the longhorn.yaml manifest file.
4. Add Kubefile
5. Run ```sealer build -f Kubefile -t longhorn .  ```
1. Run  the longhorn image with sealer.
2. wait all pods are up status
3. add a nginx pod with a PVC with longhorn storageclass.
4. Run ```kubectl  get svc -n longhorn-system```  to get ```longhorn-frontend  ``` svc cluster-ip, and browser it when the nginx pod is up.
5. We can see the nginx's log storaged in longhorn.
NONE
> add longhorn image support

- test/sealer_apply_test.go
- test/suites/apply/apply.go
- test/suites/apply/fixtures/config_plugin_for_test.yaml
- test/suites/build/build.go
- test/suites/build/fixtures/cloud_build/Kubefile
- test/suites/build/fixtures/cloud_build/imageList
- test/suites/build/fixtures/lite_build/Kubefile
- test/suites/image/image.go
- test/testhelper/settings/settings.go
v2 Infra module has not been upgraded, and the test also temporarily shields infra test;
Because infra has not implemented V2 cluster to pull infra, and v2 Apply is compatible with v1, the test will not be upgraded to v2 for the time being.
Add debug mode to display debug logs for e2e tests.
> optimize v2 test

- pkg/runtime/init.go
- pkg/runtime/masters.go
- pkg/runtime/nodes.go
- pkg/runtime/registry.go
- utils/iputils.go
- utils/ssh/ssh.go
if the node to be removed is the execution machine, kubelet, ~./kube and apiServer host will not be removed
> fix deletion failure if the node to be deleted is the executing machine

- pkg/runtime/init.go
- pkg/runtime/kubeadm_config.go
- pkg/runtime/masters.go
- pkg/runtime/nodes.go
- pkg/runtime/reset.go
- pkg/runtime/utils.go
fix `$rootfs/etc/kubeadm.yml' only partial kubeadm configuration causes failure #1046 
`etc/kubeadm.yml` instead of `kubeadm-config.yaml`,`kubeadm-join-config.yaml`
> fix `$rootfs/etc/kubeadm.yml' only partial kubeadm configuration causes failure

- pkg/config/config.go
fix failure when config directory does not exist, `utils.WriteFile` function will create all directories.
> fix failure when config directory does not exist

- apply/processor/create.go
- apply/processor/delete.go
- apply/processor/scale.go
- apply/processor/upgrade.go
- apply/scale.go
- pkg/filesystem/filesystem.go
- pkg/filesystem/filesystem_test.go
- pkg/infra/aliyun/ali_provider.go
- pkg/runtime/init.go
- pkg/runtime/kubeadm_config_test.go
- pkg/runtime/kubeadm_runtime.go
- pkg/runtime/masters.go
- pkg/runtime/nodes.go
- pkg/runtime/registry.go
- pkg/runtime/reset.go
- pkg/runtime/upgrade.go
- types/api/v2/cluster_types.go
- utils/yaml.go
- unmount rootfs is executed when the sealer delete -m command deletes some nodes.
- delete duplicate function.
- desired Clusterfile is saved before the runtime during cluster create or scale up.
> fix the unmount rootfs step is not performed on the scale down node.

- build/buildkit/buildimage/build_image.go
- pkg/parser/parser.go
- utils/env.go
below is my test kubefile: 
```
FROM kubernetes:v1.19.8
ARG value=sealer
ARG MY_ARG=abc
ARG MY_*ARG=abc # not support such key format.will ignoring this key.
ARG ddd= # default value is "".
ARG name=testname \
,PASSWORD1=PASSWORD1,\
aptget=update 
COPY aa .
COPY charts charts
RUN echo ${name}
RUN echo ${MY_ARG}
CMD echo ${PASSWORD1}
```
> build arg instruction support newline list input

- apply/run.go
- common/structs.go
- pkg/guest/guest.go
- sealer/cmd/build.go
- sealer/cmd/run.go
- types/api/v2/cluster_types.go
kubefile:
```shell
FROM kubernetes:v1.19.8
ARG Version=4.0.0 # set default version is 4.0.0, this will be used to install mongo application.
COPY mongo manifests # mongo dir contains many mongo version yaml file.
CMD kubectl apply -f mongo-${Version}.yaml # use Version arg to install mongo application.
```
overwrite args of CMD instruction from kubefile at run stage.
examples:
use this arg directly via cmdline :
`
sealer run --cmd-args Version=5.1.1  -m 172.16.0.227 -p passsword my-mongo:v1
`
use it via clusterfile:
```yaml
apiVersion: sealer.cloud/v2
kind: Cluster
metadata:
spec:
cmd_args:
- Version=4.9.0
hosts:
- ips:
- 172.16.0.227
image:  my-mongo:v1
ssh:
passwd: passsword
port: "22"
user: root
```
priority order：
sealer …
> set cmd arg for sealer run 

- apply/apply.go
if cluster name is empty in Clusterfile,
`sealer delete -f Clusterfile` will cause /var/lib/sealer/data dir deleted
> fix if cluster name is empty, sealer delete will cause /var/lib/sealer/data dir deleted

- build/buildkit/buildinstruction/mount.go
- utils/mount/overlay2.go
Background :
some linux kernel  dont support overlay2 default option index=on. that is if "/sys/module/overlay/parameters/index" is "Y"
,will cause the mount to fail。
> fix: add index=off option for overlay2 mount

- applications/nydus/nydusdfile/serverstart.sh
- pkg/filesystem/cloudfilesystem/nydus.go
- utils/iputils.go
Signed-off-by: lihongnan <hongnan.lhn@alibaba-inc.com>
Get localIP and set nydusd host config Automatically.
Nydusd need to set the IP of nydusdserver as host config in httpserver.json, and it is unfriendly to modify the nydusd configs manually.
NONE
> nydus: get localIP and set nydusd host config Automatically

- build/cloud/cloud_builder.go
- common/common.go
collect operator images via remount registry.
because runtime apply registry not mount the rootfs/registry as lower layer. if we want to collect operator images, we must remount the dir rootfs/registry for collecting differ of the overlay upper layer.
> fix:remount registry of rootfs to cache images when cloud build

- build/buildkit/buildimage/build_image.go
- build/buildkit/buildimage/shadow.go
- pkg/image/save/interface.go
- pkg/image/save/save.go
- pkg/image/save/save_test.go
- pkg/image/save/util.go
- utils/docker_config.go
sealer build support multi-user logic to pull docker images
trigger: 
if build context contains file named at "imageListWithAuth.yaml",and its format like below, will trigger sealer build to pull docker images, its work process like `COPY imageList manifests`.
```yaml
- registry: registry.cn-shanghai.aliyuncs.com
username: user1
password: pw
images:
- registry.cn-shanghai.aliyuncs.com/xxx/xxx1:v1.1
- registry.cn-shanghai.aliyuncs.com/xxx/xxx2:v1.1
- registry: registry.cn-shanghai.aliyuncs.com
username: user2
password: pw
images:
- registry.cn-shanghai.aliyuncs.com/xxx/xxx3:v1.1
- registry.cn-shanghai.aliyuncs.com/xxx/xxx4:v1.1
```
filed `registry` is optional , if not present will use the default "docker.io" as its domain name. if len (images)==0 will skip this section.
below is my build …
> feat:sealer build support multi-user logic to pull docker images

- pkg/plugin/cluster_check_plugin.go
- pkg/plugin/etcd_backup_plugin.go
- pkg/plugin/hostname_plugin.go
- pkg/plugin/labels.go
- pkg/plugin/plugin.go
- pkg/plugin/shell_plugin.go
- pkg/plugin/taint_plugin.go
- pkg/plugin/taint_plugin_test.go
- pkg/plugin/utils.go
taint plugin:
```yaml
apiVersion: sealer.aliyun.com/v1alpha1
kind: Plugin
metadata:
name: taint
spec:
type: Taint
action: PreGuest
data: |
192.168.0.2 key1=value1:NoSchedule
192.168.0.2,192.168.0.3,192.168.0.4 key2=value2:NoSchedule
192.168.0.2-192.168.0.4 key3:NoSchedule
192.168.0.2 key4=:NoSchedule
192.168.0.2 key5:NoSchedule-
192.168.0.2 key6=value6:NoSchedule-
192.168.0.2 key7=:NoSchedule-
```
> Feat: taint plugin

- applications/nydus/nydusdfile/serverstart.sh
- pkg/filesystem/cloudfilesystem/nydus.go
bugfix: fix an error about async in mountNydusRootfs
When the node running sealer is one of masters, the node maybe run nydusdInitCmd before scp nydud dir to other nodes finish. It will scp all files in rootfs because the nydusd src dir is the same as target dir. So change the nydusd src dir to be different from nydusdDir.
NONE
> nydus:fix an error about async in mountNydusRootfs

- docs/site/src/docs/advanced/use-clusterfile.md
- docs/site/src/zh/getting-started/using-clusterfile.md
- pkg/env/env.go
- pkg/env/env_test.go
host env to overwrite global env;
list env is separated by a semicolon
```shell
env:
- docker_dir=/var/lib/docker
- ips=192.168.0.1;192.168.0.2;192.168.0.3 #ips=[192.168.0.1 192.168.0.2 192.168.0.3]
hosts:
- ips: [ 192.168.0.2 ]
roles: [ master ] # add role field to specify the node role
env: # overwrite some nodes has different env config, arrays are separated by semicolons
- docker_dir=/data/docker
- ips=192.168.0.2;192.168.0.3
```
> host env to overwrite global env, and list env is separated by a semicolon

- .github/workflows/site.yml
- docs/site/README.md
- docs/site/src/zh/getting-started/using-clusterfile.md
Incorrect use of '{{}}' caused the vuepress build to fail: https://github.com/alibaba/sealer/runs/5593882562?check_suite_focus=true
when changing site documentation, perform the 'npm run build' step to prevent site updates from failing because of the change.
> fix vuepress error

- pkg/runtime/kubeadm.go
- pkg/runtime/kubeadm_runtime.go
change to kubeadm V1beta3 when k8s verison gt 1.23.0
> change to kubeadm V1beta3 when k8s verison gt 1.23.0

- types/api/v1/cluster_types.go
- utils/aes.go
- utils/ssh/connect.go
- utils/ssh/ssh.go
- utils/ssh/sshcmd_test.go
- utils/yaml.go
The plaintext password in Clusterfile is insecure. Use AES to entrypt it.
Fixes #1201 
sealer run kubernetes:v1.19.8 --masters 10.0.71.100 --passwd xxxx
sealer delete --all --force
As my test environment imit. I only test with run and delete.
> feat: ssh passwd in clusterfile encrypt(#1201)

- apply/applydriver/local.go
- apply/processor/create.go
- apply/processor/install.go
- apply/run.go
- common/structs.go
- pkg/config/config.go
- pkg/filesystem/cloudfilesystem/nydus.go
- pkg/filesystem/cloudfilesystem/overlay2.go
- pkg/filesystem/cloudfilesystem/utils.go
- pkg/filesystem/cloudimage/cloudimage.go
- pkg/gen/gen.go
- pkg/guest/guest.go
- pkg/runtime/init.go
- pkg/runtime/utils.go
- sealer/cmd/run.go
- utils/platform/cpu.go
- utils/ssh/platform.go
- pull images of all required architecture when apply;
- Fix failure of config for multiple arch;
- Move render env to mount images step;
- run creates new cluster information instead of using the cluster info of the clusterfile in the image;
- run command use `--cluster-name` to set cluster name;
- apply must support the local architecture，because of multiple architectures, the kubectl of fetch cannot be executed. It is - modified to obtain it from 'rootfs/bin/kubectl';
- fix a little bug.
> support multi arch run

- docs/site/src/docs/getting-started/using-clusterfile.md
- docs/site/src/zh/getting-started/using-clusterfile.md
- go.mod
- pkg/env/env.go
- pkg/env/test/template/test.yaml.tmpl
- vendor/modules.txt
[sprig template function for GO's template](http://masterminds.github.io/sprig/)
base64 encode or base64 decode:
```yaml
{{b64enc "qwertyuiop"}}
{{b64dec "cXdlcnR5dWlvcA=="}}
{{b64enc .IP}}
```
> support sprig template function for GO's template

- .github/workflows/auto-build.yml
Fix incorrect kubeadm configuration generated by auto-build:
Coredns Image path changed from 'core' to 'coredns/coredns' :
https://github.com/kubernetes/kubernetes/pull/96429/files#diff-afb644eceb2c0d53027d3e3815f43f489b31b34d18f5402a626f2fbfd4b6eb52R326
> fix auto build

- pkg/runtime/upgrade.go
sealer run kubernetes:v1.19.8 with app empty dir ,like dashboard,   
if want to upgrade to kubernetes:v1.19.9: `kubectl drain --ignore-daemonsets  --delete-local-data`
if want to upgrade to kubernetes:v1.20.4: `kubectl drain --ignore-daemonsets --delete-emptydir-data`
> bugfix: add different  flag for upgrade drain cmd via k8s version

- build/buildimage/utils.go
- pkg/parser/parser.go
- pkg/parser/parser_test.go
- utils/collector/local_context.go
1, support copy dest with file name
2.not panic if decode line failed
```shell
FROM kubernetes:v1.19.8
COPY cont/* contp
COPY a.txt pp/a.txt
COPY a.txt a.txt
COPY a/b.txt  etc/b.txt 
COPY ptest .
COPY dashboard.yaml manifests
CMD kubectl apply -f manifests/dashboard.yaml
```
> bugfix: support copy dest with file name

- cmd/sealer/cmd/apply.go
- cmd/sealer/cmd/build.go
- cmd/sealer/cmd/cert.go
- cmd/sealer/cmd/check.go
- cmd/sealer/cmd/debug.go
- cmd/sealer/cmd/delete.go
- cmd/sealer/cmd/exec.go
- cmd/sealer/cmd/gen.go
- cmd/sealer/cmd/images.go
- cmd/sealer/cmd/inspect.go
- cmd/sealer/cmd/join.go
- cmd/sealer/cmd/load.go
- cmd/sealer/cmd/login.go
- cmd/sealer/cmd/merge.go
- cmd/sealer/cmd/prune.go
- cmd/sealer/cmd/pull.go
- cmd/sealer/cmd/push.go
- cmd/sealer/cmd/rmi.go
- cmd/sealer/cmd/root.go
- cmd/sealer/cmd/run.go
- cmd/sealer/cmd/save.go
- cmd/sealer/cmd/search.go
- cmd/sealer/cmd/tag.go
- cmd/sealer/cmd/upgrade.go
- cmd/sealer/cmd/version.go
Currently, the seal command usage may be not so explicit. This pull request tries to polish the command description and introduce more readability.
In addition, this pull request use the unique key word `CloudImage`. CloudImage, Kubefile, Clusterfile is the reserved word of sealer project. We should maintain these for brand.
none
none
none
> cmd: polish cmd discription to add user readablity

- .github/workflows/auto-build.yml
- pkg/runtime/registry.go
Optimize the automated build action, support containerd CRI,:
- There are two CRI types supported in the k8s [v1.20-v1.24.0) version: [ docker | containerd ]:
[Build command](https://github.com/sealerio/sealer/issues/1242): /imagebuild ${version} ${cri}
Example: /imagebuild v1.22.4 docker or /imagebuild v1.22.4 containerd.
Return the image name after the build is successful:
- **CRI use docker**: kubernetes:${version} (cni: calico), kubernetes:${version}-alpine (without cni);
- **CRI: containerd**: kubernetes-containerd:${version} (cni: calico), kubernetes:${version}-alpine (without cni).
ex.: 
- Docker is used for images below k8s v1.20, and containerd is used for images of v1.24 and above.
[Build command](https://github.com/sealerio/sealer/issues/1242): /imagebuild ${version}
Example: …
> optimize automated build actions, optimize scripts

- cmd/sealer/cmd/images.go
update size unit with GiB, MiB and KiB.
Following the accurate size definition:
none
none
none
none
> fix: update size unit with GiB, MiB and KiB

- pkg/plugin/plugins.go
- pkg/plugin/utils.go
Background:
plugins which set in clusterfile and also existed in the cloud image, will be executed twice. so we need to remove the  duplicated plugins at load stage.
fixes https://github.com/sealerio/sealer/issues/1460
> bugfix: add deduplication operation for plugin load

- docs/commandline/sealer.md
- docs/commandline/sealer_apply.md
- docs/commandline/sealer_build.md
- docs/commandline/sealer_cert.md
- docs/commandline/sealer_check.md
- docs/commandline/sealer_completion.md
- docs/commandline/sealer_debug.md
- docs/commandline/sealer_debug_clean.md
- docs/commandline/sealer_debug_node.md
- docs/commandline/sealer_debug_pod.md
- docs/commandline/sealer_debug_show-images.md
- docs/commandline/sealer_delete.md
- docs/commandline/sealer_exec.md
- docs/commandline/sealer_gen-doc.md
- docs/commandline/sealer_gen.md
- docs/commandline/sealer_images.md
- docs/commandline/sealer_inspect.md
- docs/commandline/sealer_join.md
- docs/commandline/sealer_login.md
- docs/commandline/sealer_merge.md
- docs/commandline/sealer_prune.md
- docs/commandline/sealer_pull.md
- docs/commandline/sealer_push.md
- docs/commandline/sealer_rmi.md
- docs/commandline/sealer_run.md
- docs/commandline/sealer_save.md
- docs/commandline/sealer_search.md
- docs/commandline/sealer_tag.md
- docs/commandline/sealer_upgrade.md
generate sealer commandline document with cobra. this could update the doc with the latest sealer code.
In the future, I wish to automatically update the command doc with github actions. Then all developers and maintainers only need to care about the cobra code quality and care litter about the command line doc.
And the cobra auto doc generation will keep the consistency. 
none
none
none
none
> docs: update sealer command document via cobra

- pkg/image/default_image.go
- pkg/image/util.go
- pkg/image/util_test.go
Fixes #1459 
only keep url host at config file for authorization reused if user try login with full url string.
> bugfix: set wrong auth domain at sealer login

- apply/apply.go
- apply/processor/gen.go
- apply/run.go
- apply/scale.go
- cmd/sealer/cmd/delete.go
- cmd/sealer/cmd/join.go
- cmd/sealer/cmd/upgrade.go
- pkg/clusterfile/util.go
- pkg/infra/aliyun/ali_provider.go
- utils/yaml/yaml.go
1. add ssh auth flag and env for sealer join.
2. add env flag for sealer delete.
3. split cluster v1 and cluster v2 save logic at Clusterfile saving stage.
4. avoid adding empty struct filed  of Clusterfile.
fixes #1469 
test success  on my side:
all cluster node use the same password:
```shell
sealer run kubernetes:v1.21.12 -m 172.16.0.200 -p password
sealer join kubernetes:v1.21.12 -n 172.16.0.201
sealer delete -n 172.16.0.201
```
```shell
sealer run kubernetes:v1.21.12 # local host as master0, no need to set password
sealer join kubernetes:v1.21.12 -n 172.16.0.201 -p password123 # if join another node, need to set password.
sealer delete -n 172.16.0.201
```
all cluster node use the different  password:
```shell
sealer run kubernetes:v1.21.12 -m 172.16.0.200 -p password
sealer join …
```
> bugfix: add auth flag for cluster scale

- pkg/runtime/registry.go
`sh init-registry.sh` brings incompatibility on Ubuntu 20.04 LTS. We see that in init-registry.sh there is a shenbang `#!/bin/bash`.  And when using `sh` to execute file, there will be some places displaying:
```
+ check_registry
+ n=1
init-registry.sh: 44: cannot open =: No such file
+ n 3
init-registry.sh: 44: n: not found
```
We update that with `./init-registry`, and it would be the default shenbang `#!/bin/bash` to execute the shell file.
fixes https://github.com/sealerio/sealer/issues/1507
none
none
> shell: make sh and /bin/bash compatible on more OS(Ubuntu)

- pkg/env/env.go
使用go标准库的template能力，而非来源于html库的。
在测试中发现，html库的template行为，与go标准库所描述的并不一致。例如，and函数的go标准库描述如下：
```
and
Returns the boolean AND of its arguments by returning the
first empty argument or the last argument. That is,
"and x y" behaves as "if x then y else x."
Evaluation proceeds through the arguments left to right
and returns when the result is determined.
```
这也符合常识，当AND的左操作字为false时，将不会再去检查右操作字，这在很多场景下是有用的，例如：
{{ if and (.HostIPFamily) (eq .HostIPFamily "6") }}，这一行判断可以cover住HostIPFamily未定义的场景。
然而，当我使用html库的template来渲染时，它总是渲染失败。
因此，我希望替换sealer中的template库：https://pkg.go.dev/text/template，使用go标准库将符合大多数人的认知。
> Use template from go standard library rather than html's

- cmd/sealer/cmd/root.go
Every time when we support end user, I found that there are always command usage information and duplicated error. It makes information less explicit. We make the cobra not to print usage info and just print one time of error. 
none
none
none
none
> cmd: update cobra command option to silence usage and error

- .github/release-drafter.yml
- .github/workflows/release.yml
Currently, we manually write the release draft every time when we do version release works, which is consume much times.
and this github action will distinguish different pull request types via labels, and write release draft automatically.
NONE
add github action named "release-drafter/release-drafter" to write release draft automatically.
> chore: add github action for writing release draft automatically

- apply/run.go
- cmd/sealer/cmd/run.go
1. filter the empty string to make sure the cluster node ip is valid.
2. set local ip address as master0 default ip if user input is empty.
run clusterImage without set IP address and auth info to see if it is success.
`sealer run kubernetes:v1.19.8`
> Bugfix: filter the empty string to make sure the cluster node ip is valid

- pkg/runtime/runtime.go
- pkg/runtime/utils_test.go
Signed-off-by: starComingup <1225067236@qq.com>
We need a field to distinguish k0s、k3s、k8s runtime tool.
Fixed #1549 
Add a field in runtime Metadata struct.
```
root@ecs-66c3:~/go/src/github.com/sealerio/sealer# go test -v -run TestLoadMetadata ./pkg/runtime/
=== RUN   TestLoadMetadata
=== RUN   TestLoadMetadata/test_metadata_file_from_rootfs
--- PASS: TestLoadMetadata (0.00s)
--- PASS: TestLoadMetadata/test_metadata_file_from_rootfs (0.00s)
PASS
ok  	github.com/sealerio/sealer/pkg/runtime	0.011s
```
NONE
> feat: add a field to distinguish runtime tool and add TestLoadMetadata unit test.

- apply/scale.go
- apply/scale_test.go
- types/api/v2/cluster_types.go
1. `make` will add default value  "" as one element , while  empty string is meaningful for k8s api server alt name cert.
thus, it will fail to run `kubeadm init`.
2. skip validate masters ip if only scale up node.
> bugfix: delete empty ip string which will be added to api server cert alt name

- apply/run.go
- pkg/debug/clusterinfo/clusterinfo.go
- utils/net/iputils.go
Usually , we use builtin func `make` to allocates and initializes a slice with the type and the length.
golang will init the default value of the slice type with the length and the capacity .
examples: `make([]string,2)`  that means we got a slice ["",""] which length and capacity both equal 2.
after do `append`, the length will grow, but If  it has no sufficient capacity,  a new underlying array will be allocated with the new length and capacity. then, the new slice  looks like : `["","","test"]` with length and capacity equal 3.
so, in some case ,  if the default value is meaningful , it will cause some uncontrollable bug.
set the slice with default length 0, append will start form the length index.
Or use `var ` to declare a variable.
> fix: add default length for slice

- Dockerfile
- Makefile
This pr implements building in docker.
Q: Why we need this?
A: Sealer must be built on linux. Otherwise there will be storage problem.
> optimize: build in docker

- pkg/runtime/kubernetes/join_nodes.go
- pkg/runtime/kubernetes/registry.go
1.fix runtime wrong config when join node: wrong kubeadm config when join node, seems this using default config when merging kubeadm.yaml `criSocket: /var/run/dockershim.sock`
2.  wrong kubelet auth file path: if /var/lib/kubelet is not exist, /var/lib/kubelet will be a file with config.json as its content. that will cause 401 .
> bugfix: fix runtime wrong config when join node

- cmd/sealer/cmd/login.go
- cmd/sealer/cmd/logout.go
> cmd: add logout and remove useless var of login

- common/common.go
- pkg/filesystem/cloudfilesystem/utils.go
- pkg/runtime/kubernetes/utils.go
- utils/os/fs.go
Part of #1607.
Use exec.LookPath() to search kubectl binary globally on the system,
this command may not be installed under `/usr/bin` by default.
Signed-off-by: Yuanhong Peng <yummypeng@linux.alibaba.com>
> optimization: be rigorous when check if kubectl command exists

- hack/build.sh
sealer version
```
{"gitVersion":"latest","gitCommit":"45787f39","buildDate":"2022-08-25 08:01:37","goVersion":"go1.18.5","compiler":"gc","platform":"linux/amd64"}
```
```
{"gitVersion":"unknown","gitCommit":"45787f39","buildDate":"2022-08-25 08:01:37","goVersion":"go1.18.5","compiler":"gc","platform":"linux/amd64"}
```
> change sealer default version to "unknown" instead of "latest".

- pkg/imageengine/buildah/init.go
Set a default storage config for containers/images
> fix: set a default storage conf

- utils/mount/overlay2.go
> fix: ensure overlay loaded

- pkg/prune/build_pruner.go
- utils/mount/mount_service.go
Umount the tmp overlay device by device path not mountpoint.
In the sealer (<=v0.8.6), sealer prune will prune build-tmp-data by umount and remove, but umount overlay type monuntpoint will failed. maybe we should just umount the device name not mountpoint.
I find out, in the master branch, the command `prune` has dropped. should i fix in the 0.8.6?
try to fix #1697
> Fix: overlay umount error by mountpoint

- apply/driver/local.go
- apply/processor/create.go
- apply/processor/delete.go
- apply/processor/gen.go
- apply/processor/scale.go
- apply/processor/utils.go
- cmd/sealer/cmd/cluster/apply.go
- cmd/sealer/cmd/cluster/delete.go
- pkg/runtime/interface.go
- pkg/runtime/k0s/common.go
- pkg/runtime/k0s/delete_masters.go
- pkg/runtime/k0s/delete_nodes.go
- pkg/runtime/k0s/join_masters.go
- pkg/runtime/k0s/join_nodes.go
- pkg/runtime/k0s/registry.go
- pkg/runtime/k0s/reset.go
- pkg/runtime/k0s/runtime.go
- pkg/runtime/k0s/upgrade.go
- pkg/runtime/kubernetes/runtime.go
After k0s init step, there are update/join/delete/reset interface which need to implement, this PR finish all k0s cluster install action.
NONE, but a step for #1399
> Feature: k0s runtime remain work

- cmd/sealer/cmd/image/rmi.go
try to fix sealer rmi with flag error
#1710
> Fix: cmd rmi images with flags

- apply/driver/local.go
- apply/processor/create.go
- apply/processor/gen.go
- cmd/sealer/cmd/image/build.go
- cmd/sealer/cmd/image/login.go
- cmd/sealer/cmd/image/logout.go
- cmd/sealer/cmd/image/pull.go
- pkg/define/options/options.go
- pkg/imageengine/buildah/build.go
- pkg/imageengine/buildah/commit.go
- pkg/imageengine/buildah/engine.go
- pkg/imageengine/buildah/from.go
- pkg/imageengine/buildah/get_annotation.go
- pkg/imageengine/buildah/images.go
- pkg/imageengine/buildah/inspect.go
- pkg/imageengine/buildah/login.go
- pkg/imageengine/buildah/logout.go
- pkg/imageengine/buildah/pull.go
- pkg/imageengine/buildah/push.go
There are general options for cmds could be put into the engine. Instead of initialize one for every command.
And this could help to fix redefine problem.
@VinceCui @kakaZhou719 FYI.
> optimize the buildah options

- utils/mount/mount_service.go
When mountinfo.GetMounts return an empty []*info, caused a panic.
#1717
> Fix: image mount panic

- pkg/image/save/save.go
Signed-off-by: HIHIA <283304489@qq.com>
check tmpBlob length to avoid slice bounds out of range
Fixes #1692
> Fix: check tmpBlob length

- .golangci.yml
Due to the library "gpgme" can't not be included well in apple silicon(m1), it will be problem when do golangci-lint.
> fix ci lint

- pkg/runtime/kubernetes/init.go
- utils/ssh/sshcmd.go
When sealer binary runs into an error, it is quite important for sealer to throw out the detailed and explicit error message. While I found that in lots of cases, sealer binary always throws an error message containing `exit status 1`, which seems to meaningless and helpless for any end-user. Here is an issue list which reflect the situation above:
* https://github.com/sealerio/sealer/issues/1618
* https://github.com/sealerio/sealer/issues/1580 
* https://github.com/sealerio/sealer/issues/1519
* https://github.com/sealerio/sealer/issues/1437
* and so on
This pull request changes such situation with outputting the stderr information. If we call some shell scripts, generally the error message would be always thrown into the os.Stderr. And if …
> fix: remove exit status 1 and display stderr info

- pkg/runtime/k0s/delete_masters.go
- pkg/runtime/k0s/delete_nodes.go
- pkg/runtime/k0s/init.go
- pkg/runtime/k0s/join_masters.go
- pkg/runtime/k0s/join_nodes.go
- pkg/runtime/k0s/reset.go
- pkg/runtime/k0s/runtime.go
Signed-off-by: starComingup <1225067236@qq.com>
k0s nodes reset do not need to specify `--config`  so this made sealer delete failed. In this PR, resolve this bug.
And master nodes will set default config path:`/etc/k0s/k0s.yaml/` which same as our config path,
NONE
> fix k0s reset bug.

- build/layerutils/manifests/manifests.go
- pkg/client/docker/auth/auth.go
- pkg/clusterfile/clusterfile.go
- pkg/clusterfile/util.go
- pkg/config/config.go
- pkg/filesystem/cloudfilesystem/utils.go
- pkg/filesystem/clusterimage/clusterimage.go
- pkg/image/save/filesystem.go
- pkg/imageengine/buildah/build.go
- pkg/imageengine/buildah/from.go
- pkg/plugin/etcd_backup_plugin.go
- pkg/plugin/plugins.go
- pkg/plugin/test/label_nodes.go
- pkg/runtime/kubernetes/kubeadm/kubeadm_config_test.go
- pkg/runtime/utils.go
- pkg/runtime/utils_test.go
- test/e2e_test.go
- test/suites/build/build.go
- test/testhelper/utils.go
- utils/archive/compress_test.go
- utils/mount/default.go
- utils/os/fs.go
- utils/os/fs/filesystem.go
- utils/os/readers.go
- utils/os/writers.go
- utils/ssh/connect.go
- utils/ssh/scp.go
- utils/yaml/yaml.go
The `io/ioutil` package has been deprecated in Go 1.16 (See https://pkg.go.dev/io/ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.
Replaces:
- `ioutil.Discard` => `io.Discard`
- `ioutil.NopCloser` => `io.NopCloser`
- `ioutil.ReadAll` => `io.ReadAll`
- `ioutil.ReadDir` => `os.ReadDir` (returns a slice of `os.DirEntry` rather than a slice of `fs.FileInfo`, this may improve performance in some cases as `os.ReadDir` is more efficient [\[1\]])
- `ioutil.ReadFile` => `os.ReadFile`
- `ioutil.TempDir` => `os.MkdirTemp`
- `ioutil.TempFile` => `os.CreateTemp`
- `ioutil.WriteFile` => `os.WriteFile`
[\[1\]]: https://pkg.go.dev/io/ioutil#ReadDir
This PR is a non-breaking change.
> refactor: move from io/ioutil to io and os packages

- cmd/sealer/cmd/utils/cluster_test.go
- cmd/sealer/cmd/utils/hosts_test.go
- cmd/sealer/cmd/utils/validate_test.go
> Add cmd ut

- pkg/cluster-runtime/installer.go
- pkg/cluster-runtime/scale.go
- pkg/cluster-runtime/uninstall.go
- pkg/cluster-runtime/utils.go
- pkg/registry/configurator.go
- pkg/registry/driver.go
- pkg/registry/singleton.go
1. optimize cluster runtime : move out uninstall and scale process 
2. load registry data from cluster image if its type is app-installer.
> optimize cluster runtime

- cmd/sealer/cmd/alpha/cert.go
- pkg/clusterfile/util.go
bugfix: use new clusterfile logic to update api server cert
> bugfix: use new clusterfile logic to update api server cert

- cmd/sealer/cmd/cluster/delete.go
- cmd/sealer/cmd/cluster/join.go
- cmd/sealer/cmd/cluster/run.go
- pkg/cluster-runtime/installer.go
- pkg/cluster-runtime/scale.go
- pkg/cluster-runtime/uninstall.go
- pkg/cluster-runtime/utils.go
- pkg/imagedistributor/mount.go
- pkg/imagedistributor/scp_distributor.go
- utils/platform/platform.go
- utils/ssh/platform.go
1. support load plugins from cluster image before image distributor.
2. save all mount info, like mount dir, platform, targethosts, after mount cluster image 
3. confirm first when sealer delete
> optimize: load plugins before image distributor

- common/common.go
- pkg/infradriver/ssh_infradriver.go
- pkg/infradriver/ssh_infradriver_test.go
> support default HostIp

- pkg/cluster-runtime/hook.go
- pkg/runtime/kubernetes/utils.go
1. support '|' for hook's scope
2. fix clean /var/lib/kubelet device busy bug.
> Fix some bugs

- cmd/sealer/cmd/cluster/cluster.go
- cmd/sealer/cmd/cluster/run-app.go
- cmd/sealer/cmd/cluster/run.go
- cmd/sealer/cmd/types/types.go
- common/common.go
- pkg/cluster-runtime/apps.go
- pkg/cluster-runtime/installer.go
as we know , we use sealer run to launch cluster image including k8s cluster and build-in apps. meanwhile, sealer also support to build cluster image which image type is application that will only launch build-in apps.
So I suggest that we can separate these two sealer run process and support an additional command.
> support sealer run-app sub command

- cmd/sealer/cmd/alpha/alpha.go
- cmd/sealer/cmd/cluster/cert.go
- cmd/sealer/cmd/cluster/cluster.go
move sealer cert command to cluster module
> move sealer cert command

- cmd/sealer/cmd/image/save.go
- pkg/infradriver/ssh_infradriver.go
- pkg/infradriver/ssh_infradriver_test.go
set default sealer save format as `oci-archive`, thats because we need `ImageAnnotations` to launch cluster image.
> bugfix: image save use ociv1 format

- pkg/imagedistributor/mount.go
Bug: if run fail, need clean /var/lib/sealer/data/linux_amd64_ manualy
#1801 
at mount.go, if /var/lib/sealer/data/linux_amd64_ exists,remove it before mount
I made a test,if linux_amd64_ exits, we can see it can be deleted before mount:
> When sealer run, clean /var/lib/sealer/data/linux_amd64_ if exists

- cmd/sealer/cmd/cluster/join.go
- cmd/sealer/cmd/cluster/scale-up.go
- pkg/clusterfile/clusterfile.go
fix:If join a node fail, it will be stored in ClusterFile and can't join it again
fix:If join a node fail, it will be stored in ClusterFile and can't join it again, unless remove it from ClusterFile manually
#1802  
At the beginning of the sealer join cmd,I store the default Clusterfile,if there exits an error,restore the ClusterFile to the default file,the second defer func will infect the first defer func and the value of 'err',so I change it to 'e'.
I have made some tests,if cmd fail,the Clusterfile will be the default one:
before sealer join:
executing sealer join:
if sealer join cmd fail,the Clusterfile will be the default:
> fix:If join a node fail, it will be stored in ClusterFile and can't join it again

- cmd/sealer/cmd/cluster/apply.go
- cmd/sealer/cmd/cluster/run.go
Fix the sealer run command failure
> fix:sealer run bug

- cmd/sealer/cmd/cluster/apply.go
- cmd/sealer/cmd/cluster/join.go
- cmd/sealer/cmd/cluster/run-app.go
- cmd/sealer/cmd/cluster/scale-up.go
- pkg/checker/node_checker.go
- pkg/checker/pod_checker.go
- pkg/checker/svc_checker.go
- pkg/client/k8s/client.go
- pkg/runtime/k0s/delete_masters.go
- pkg/runtime/k0s/delete_nodes.go
> support cluster scale up via sealer apply cli

- cmd/sealer/cmd/cluster/delete.go
> support delete -f

- pkg/config/config.go
- pkg/imagedistributor/scp_distributor.go
1. should not trim Config's empty line;
2. if no registry dir exist in AppImage, should skip scp it.
> Fix: 1. should not trim Config's empty line;     2. if no registry dir exist in AppImage, should skip scp it.

- common/common.go
- pkg/cluster-runtime/hook.go
- pkg/container-runtime/docker.go
- test/testhelper/helper.go
- utils/exec/exec.go
- utils/ssh/sshcmd.go
Support skip clean hooks when cluster workspace not exist. This can improve the robust of clean.
Sometimes the directory has been cleaned up, but if the hook is executed again, an error will be reported because there is no file. This makes the logic for cleaning up nodes non-reentrant. So changed to, if there is no working directory, skip hook execution
> Support skip clean hooks when cluster workspace not exist.

- build/buildimage/middleware.go
- cmd/sealer/cmd/image/build.go
- pkg/define/options/options.go
add build flag `--image-list-with-auth` to support download container images from imageListWithAuth.yaml
example:
` sealer build -t abc:v1 --image-list-with-auth imageListWithAuth.yaml`
if it set, sealer will read its content and download extra container images to rootfs.
> bugfix: download images from imageListWithAuth.yaml

- cmd/sealer/cmd/cluster/apply.go
- common/common.go
In special scenarios, we want to load images to the specified registry in advance.
This PR try to support the above feature by do these things:
add apply mode flag
support only loadImage apply mode
> support only load image apply mode

- cmd/sealer/cmd/cluster/apply.go
- cmd/sealer/cmd/cluster/delete.go
- cmd/sealer/cmd/cluster/join.go
- cmd/sealer/cmd/cluster/run-app.go
- cmd/sealer/cmd/cluster/run.go
- cmd/sealer/cmd/cluster/scale-up.go
- pkg/cluster-runtime/apps.go
- pkg/cluster-runtime/installer.go
- pkg/cluster-runtime/scale.go
- pkg/imagedistributor/interface.go
- pkg/imagedistributor/mount.go
- pkg/imagedistributor/mount_test.go
- pkg/imagedistributor/scp_distributor.go
- pkg/infradriver/ssh_infradriver.go
At present, our cluster image data is mixed with application image data and base image data, If we run multiple images at the same time, there will be conflicts.
1. Detach the mount directory
all imagedata mount directory will under below directory:
`/var/lib/sealer/data/mount/${imageName}/${platform}`
all application imagedata rootfs directory will under below directory:
`var/lib/sealer/data/${imageName}/rootfs/application/apps`
all basefs  imagedata directory will under below directory:
`var/lib/sealer/data/${imageName}/rootfs`
2. add a file lock on .sealer/application.json
> sealer run-app supports concurrent  run 

- README.md
> add image info

- build/kubefile/parser/app_handler.go
- build/kubefile/parser/utils.go
- cmd/sealer/cmd/cluster/apply.go
- cmd/sealer/cmd/cluster/cert.go
- cmd/sealer/cmd/cluster/delete.go
- cmd/sealer/cmd/cluster/join.go
- cmd/sealer/cmd/cluster/run-app.go
- cmd/sealer/cmd/cluster/run.go
- cmd/sealer/cmd/cluster/scale-up.go
- cmd/sealer/cmd/image/build.go
- pkg/cluster-runtime/hook.go
- pkg/clusterfile/clusterfile_test.go
- pkg/imagedistributor/scp_distributor.go
- pkg/registry/singleton.go
- pkg/runtime/kubernetes/init.go
- pkg/runtime/kubernetes/runtime.go
- utils/os/fs/filesystem_test.go
Signed-off-by: Lancelot <1984737645@qq.com>
"io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. [https://pkg.go.dev/io/ioutil](https://pkg.go.dev/io/ioutil)
Replaces:
```
ioutil.TempDir => os.MkdirTemp
ioutil.ReadDir => os.ReadDir
ioutil.ReadFile => os.ReadFile
ioutil.ReadAll => io.ReadAll
ioutil.TempFile => os.CreateTemp
ioutil.WriteFile => os.WriteFile
```
Same as  #1759 
Functionally zero changes to code.
> refactor: replace the deprecated package io/ioutil with os and io

- build/kubefile/parser/app_handler.go
- build/kubefile/parser/image_engine_test.go
- build/kubefile/parser/kubefile.go
- build/kubefile/parser/parse_test.go
- build/kubefile/parser/utils.go
- pkg/define/application/types.go
- pkg/define/application/v1/application.go
- pkg/define/application/version/version.go
sometimes when installing an app type cluster image, we need to configure some additional information. such as some k8s  cluster resources which cannot be directly written in the yaml file as fixed value.
if so, we nee add shell type for APP instruction, and  it does not affect the current usage.
for shell :
1. if local file is normal file and the suffix of this file ends with a ".sh", will copy it to rootfs ,and write its launch cmd in  sealer image extension at build stage.
2.  if local file is dir,   will walk though the target dir , and  collect all files which suffix is ends with a ".sh", then write its launch cmd in sealer image extension at build stage.
below is my test kubefile:
```shell
FROM scratch
APP config local://config.sh
APP my-shell local://shell 
APP dashboard …
```
> feat: add shell type for APP instruction

- cmd/sealer/cmd/cluster/apply.go
- cmd/sealer/cmd/cluster/cert.go
- cmd/sealer/cmd/cluster/delete.go
- cmd/sealer/cmd/cluster/join.go
- cmd/sealer/cmd/cluster/run-app.go
- cmd/sealer/cmd/cluster/run.go
- cmd/sealer/cmd/cluster/scale-up.go
- pkg/clusterfile/clusterfile.go
- pkg/clusterfile/clusterfile_test.go
at present , we store the cluster configuration information on the master0 local disk after we create the cluster, such as node auth info , cluster plugins, cluster env and so on .
If this file is mistakenly deleted or modified by mistake, it will be a great disaster for the maintenance of the cluster. 
so we need to store this file in the cluster to do disaster preparedness, and each time we can prioritized use the clusterfile  in the cluster for operation.
1. save clusterfile to cluster as configmap with name "sealer-clusterfile"  in namespace "kub-system".
2. modify some cmd examples
> feat: save clusterfile to the cluster 

- pkg/imageengine/buildah/push.go
#1900
No response
No response
No response
No response
> chore: delete push CLI debug message

- cmd/sealer/cmd/alpha/alpha.go
- cmd/sealer/cmd/alpha/search.go
- cmd/sealer/cmd/image/image.go
- pkg/image/reference/util.go
Support search to view the current list of supported images
1. move search to alpha
2. modify default defaultDomain and defaultRepo
> move search to alpha

- docs/design/master0-recovery.md
Master0 plays an important role in sealer cluster, it hosts many important components such as sealer builtin registry,
application images launched history and others cluster configuration files. if the master0 node is abnormal, a highly
available solution is required to recover on other master nodes.
Currently, we have plans to save clusterfile to the cluster. while for built registry ,it is still deployed a single
instances on master0 node. So the following document are mainly for built registry.
> doc: add master0 recovery design

- pkg/image/save/filesystem.go
- pkg/image/save/save.go
- pkg/image/save/utils.go
Signed-off-by: Lancelot <1984737645@qq.com>
#1881 
I use a way to find the Docker image locally whether the image has already existed in Base Image
Before
We don't need to download again
> fix: duplicate download container images that already exist in base image

- pkg/cluster-runtime/installer.go
- pkg/cluster-runtime/scale.go
- pkg/infradriver/infradriver.go
- pkg/infradriver/ssh_infradriver.go
- types/api/v2/cluster_types.go
sometimes, user wants to specify the cluster node lables field according to their business scenario. So I thought we could support this feature by configuring the desired clusterfile.
we could set labels filed in clusterfile, this will add label content to each cluster node.
```yaml
apiVersion: sealer.cloud/v2
kind: Cluster
metadata:
spec:
hosts:
- ips:
- 172.16.26.187
roles:
- node
labels:
foo: bar
ssh: {}
- ips:
- 172.16.26.188
roles:
- master
labels:
fake: labels
ssh: {}
image: registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.22.4-test
ssh:
passwd: testabs
port: "22"
user: root
status: {}
```
> feat: support to add node labels via clusterfile

- pkg/cluster-runtime/installer.go
- pkg/cluster-runtime/scale.go
- pkg/infradriver/infradriver.go
- pkg/infradriver/ssh_infradriver.go
- pkg/infradriver/utils.go
- pkg/infradriver/utils_test.go
- types/api/v2/cluster_types.go
1. add taint to cluster type
2. ClusterFile supports configuring node taint #1889
> support taint cluster node through clusterfile

- cmd/sealer/cmd/image/build.go
add imageList Flag to sealer build to support download extra container image rather than copy it to rootfs,Provide additional image download method.
eg:
sealer build -t abc:v1 --image-list imageList
> add --image-list imageList

- pkg/ipvs/ipvs.go
- pkg/ipvs/ipvs_test.go
- pkg/registry/installer.go
- pkg/registry/local.go
- pkg/runtime/kubernetes/utils.go
for registry server health path :choose "/" as default.
for registry server health schem: if registry deployed as insecure mode, health schem is "http", otherwise ,it is "https".
> set lvscare health path and health schem for registry server

- pkg/image/save/save.go
- pkg/imagedistributor/scp_distributor.go
We need to be more explicit about when we should use concurrency, and when using concurrency actually increases our chances of making mistakes. In this PR, I update these things:
1. set the concurrency of pull image is set to 1 because the bottleneck of downloading images is often in the network rather than computing resources
2. copy the registry to other master nodes, we will copy lots of small files and the bottleneck of copy registry is not in the network so we can copy multi nodes concurrently
> chore: update concurrent for some logic

- pkg/image/save/save.go
- pkg/imagedistributor/scp_distributor.go
check if the blob files for image is complete and retry to get if not
> feature: check image blob save and retry if not exist

- cmd/sealer/cmd/utils/cluster_test.go
- cmd/sealer/cmd/utils/hosts_test.go
- common/common.go
- docs/api/clusterfile.md
- docs/design/clusterfile-v2.md
- docs/design/global-config.md
- docs/design/plugin.md
- pkg/cluster-runtime/hook_test.go
- pkg/cluster-runtime/test/test.yaml
- pkg/clusterfile/clusterfile_test.go
- pkg/clusterfile/decoder_test.go
- pkg/infradriver/ssh_infradriver_test.go
- pkg/runtime/kubernetes/kubeadm/kubeadm_config_test.go
- test/suites/apply/fixtures/config_plugin_for_test.yaml
- types/api/v1/config_types.go
- utils/decode.go
- utils/test/file/Clusterfile
for cluster: replace `sealer.cloud/v2` to `sealer.io/v2` 
for plugin: replace `sealer.aliyun.com/v1alpha1` to `sealer.io/v1alpha1` 
for config: replace `sealer.aliyun.com/v1alpha1` to `sealer.io/v1alpha1`
> user sealer.io as apiversion

- pkg/define/image/v1/sealer_image_extension.go
- pkg/imageengine/buildah/inspect.go
- pkg/imageengine/buildah/sealer_image_extension.go
- pkg/imageengine/buildah/sealer_image_extension_test.go
add container image list for sealer image spec
the end users can get container image list by `sealer inspect` and the developer can get the container image list by  the key `sealer.image.container.images` from image annotations
after that, we also need to do the following:
1. parse and store the container image list when the build phase
2. add a flag for `sealer inspect` to decide whether to output the list of images because of container image list could be a huge number
> chore: add container image list for image spec

- build/kubefile/command/command.go
- build/kubefile/parser/kubefile.go
- build/kubefile/parser/parse.go
Temporary use of the CMD command.
ex:
Kubefile:
FROM docker.io/sealerio/kubernetes:v1.22.15
CMD kubectl get ns
CMD echo "AAAAAAA"
CMDS ["kubectl get node","kubectl get po -A"]
> Add CMD command to Kubefile

- pkg/config/config.go
- types/api/v1/config_types.go
`ConfigSpec.path` is where the `ConfigSpec.Data` write on, it could be the relative path of rootfs (manifests/mysql.yaml). Or work with APPName to form a complete relative path(application/apps/{APPName}/mysql.yaml)
> support specify appname for config

- build/kubefile/command/command.go
- build/kubefile/parser/app_handler.go
- build/kubefile/parser/kubefile.go
- build/kubefile/parser/parse.go
- pkg/define/image/v1/sealer_image_extension.go
- pkg/imageengine/buildah/inspect.go
- pkg/imageengine/buildah/inspect_test.go
Add `CNI`, `CRI`, `LABEL`,`KUBEVERSION` instruction for `Kubefile`
Partial fixes https://github.com/sealerio/sealer/issues/1968
> feature: enrich kubefile

- build/kubefile/command/command.go
- build/kubefile/parser/kubefile.go
- build/kubefile/parser/parse.go
- cmd/sealer/cmd/image/build.go
- pkg/application/v2app.go
- pkg/define/application/v1/application.go
- pkg/define/application/version/version.go
- pkg/define/image/v1/sealer_image_extension.go
related issue https://github.com/sealerio/sealer/issues/1968
> feature: optimize app instruction

- build/kubefile/parser/app_handler.go
- build/kubefile/parser/utils.go
- pkg/define/application/v1/application.go
- pkg/define/image/v1/sealer_image_extension_test.go
> bugfix: use deep walk to get launch files for shell and kube

- cmd/sealer/cmd/alpha/alpha.go
- cmd/sealer/cmd/alpha/mount.go
- cmd/sealer/cmd/alpha/umount.go
- cmd/sealer/cmd/utils/cluster.go
- cmd/sealer/cmd/utils/hosts.go
- pkg/imageengine/buildah/from.go
add sealer alpha mount command and support check image file
we can go to the mount directory to check the mirrored files, which can ensure that the kubefile image is built correctly.
#1742
1. support sealer alpha mount imageName/imageId
2. support sealer alpha umount imageNmae/imageId
3. support sealer alpha mount(view mount list)
> Add sealer alpha mount command

- common/common.go
- pkg/registry/local.go
- pkg/runtime/kubernetes/utils.go
> modify lvscare name

- .github/workflows/e2e-test-apply.yml
- .github/workflows/e2e-test-build.yml
- .github/workflows/e2e-test-image.yml
- .github/workflows/e2e-test-run.yml
- pkg/infra/container/client/docker/container.go
- pkg/infra/container/container.go
- pkg/infra/container/imagecontext/arm/entrypoint
- pkg/infra/container/imagecontext/base/Dockerfile
- pkg/infra/container/imagecontext/base/entrypoint
- pkg/infra/container/imagecontext/build/Dockerfile
- pkg/infra/test/container_test.go
- pkg/runtime/kubernetes/utils.go
- test/README.md
- test/e2e_test.go
- test/sealer_apply_test.go
- test/sealer_build_test.go
- test/sealer_images_test.go
- test/sealer_run_test.go
- test/suites/apply/apply.go
- test/suites/apply/fixtures/cluster_file_for_test.yaml
- test/suites/apply/fixtures/config_plugin_for_test.yaml
- test/suites/build/build.go
- test/suites/build/fixtures/lite_build/Kubefile
- test/suites/image/image.go
- test/suites/registry/registry.go
- test/testhelper/settings/common.go
- test/testhelper/utils.go
- utils/shellcommand/hostsfile.go
- utils/ssh/scp.go
feature:local e2e test and CI using github action
#1633 #1734 
Infra using docker and run containers as nodes for sealer e2e test,using github action for sealer CI.
See /test/README.md
Before we use the CI using github aciton feature, please make sure that these three variables: REGISTRY_URL={your registry},
REGISTRY_USERNAME={user name},REGISTRY_PASSWORD={password} have been setted in github's secret (for sealer login and sealer image tests).
> feat:sealer local e2e test and CI using github action

- build/kubefile/parser/line_parsers.go
support ${ARCH}
example:
Kubefile:
```yaml
FROM scratch
COPY rootfs .
COPY ${ARCH}/* .
COPY imageList manifests
LABEL "cluster.alpha.sealer.io/cluster-runtime-version"="v1.22.15"
LABEL "cluster.alpha.sealer.io/cluster-runtime-type"="kubernetes"
LABEL "cluster.alpha.sealer.io/container-runtime-type"="docker"
LABEL "cluster.alpha.sealer.io/container-runtime-version"="19.03.14"
CNI calico local://tigera-operator.yaml local://custom-resources.yaml
LAUNCH ["calico"]
```
> support ${arch}

- test/README.md
- test/sealer_apply_test.go
- test/sealer_build_test.go
- test/sealer_images_test.go
- test/sealer_run_test.go
- test/suites/apply/fixtures/cluster_file_for_test.yaml
- test/suites/apply/fixtures/config_plugin_for_test.yaml
- test/suites/build/build.go
- test/suites/build/fixtures/lite_build/Kubefile
- test/testhelper/settings/common.go
Change the test image requires changing all the relevant image names in the code, which is not very convenient. So, we can set an environment variable that changes only that variable to modify test image.
And after this PR, we can export an environment variable named IMAGE_NAME to modify all test image
#2011
> set CustomImageName to change TestImage and fix code

- .github/workflows/e2e-test-apply.yml
- .github/workflows/e2e-test-build.yml
- .github/workflows/e2e-test-image.yml
- .github/workflows/e2e-test-run.yml
fix:GitHub action for e2e-test_comment doesn't show in checks for PR, after this PR, we can use comment like:"/test all","/test run" to trigger CI and see checks on PR.
#2030
> fix:GitHub action for e2e-test_comment doesn't show in checks for PR

- .github/workflows/e2e-test-apply.yml
- .github/workflows/e2e-test-build.yml
- .github/workflows/e2e-test-image.yml
- .github/workflows/e2e-test-run.yml
- .github/workflows/go.yml
- .github/workflows/release.yml
- .github/workflows/unit-test.yml
chore: update some deprecated tools in github action
we can find some warning in workflow annotations like:
```bash
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
> chore: update some deprecated tools in github action

- build/kubefile/parser/kubefile.go
- build/kubefile/parser/parse_test.go
- build/kubefile/parser/utils.go
- build/kubefile/parser/utils_test.go
- cmd/sealer/cmd/image/build.go
- pkg/define/application/types.go
- test/sealer_build_test.go
- test/suites/build/build.go
- test/suites/build/fixtures/build_with_appcmds/Kubefile
- test/suites/build/fixtures/build_with_appcmds/install.sh
- test/suites/build/fixtures/build_with_appcmds/mixedcontext/app.yaml
- test/suites/build/fixtures/build_with_appcmds/mixedcontext/install.sh
- test/suites/build/fixtures/build_with_appcmds/shellcontext/a.sh
- test/suites/build/fixtures/build_with_appcmds/shellcontext/b.sh
- test/suites/build/fixtures/build_with_appcmds/shellcontext/c.sh
- test/suites/build/fixtures/build_with_appcmds/yamlcontext/a.yaml
- test/suites/build/fixtures/build_with_appcmds/yamlcontext/b.yaml
- test/suites/build/fixtures/build_with_appcmds/yamlcontext/c.yaml
kubefile:
```shell
FROM scratch
APP yamlapp local://yamlcontext
APP shellapp local://shellcontext
APP mixedapp local://install.sh local://mixedcontext
APPCMDS mixedapp ["kubectl apply -f app.yaml"]
LAUNCH ["mixedapp","shellapp"]
```
```
├── context
│   ├── app.yaml
│   └── install.sh
├── install.sh
├── Kubefile
├── shellcontext
│   ├── a.sh
│   ├── b.sh
│   └── c.sh
└── yamlcontext
├── a.yaml
├── b.yaml
└── c.yaml
```
if app build context is mixed, need to specify `APPCMDS` if no app type is detected.
> support mixed app type with appcmds

- cmd/sealer/cmd/image/load.go
- cmd/sealer/cmd/image/save.go
- pkg/imageengine/buildah/load.go
- pkg/imageengine/buildah/manifest.go
- pkg/imageengine/buildah/save.go
support multi arch for load and save, no need to care about the image arch.
save:  could save with id Or name.
`sealer save bf5e56e64dd9 -o abc.tar`
`sealer save abc:v1 -o abc.tar`
load:
`sealer load -i abc.tar`
> feat:support multi arch for load and save

- build/kubefile/parser/app_handler.go
> bugfix:delete tmp build dir

- cmd/sealer/cmd/cluster/run.go
- common/common.go
- pkg/cluster-runtime/hook.go
- pkg/cluster-runtime/upgrader.go
Support sealer upgrade
Distribute materials by sealer & Upgrade cluster by plugin。
```
sealer run ack-agility-registry.cn-shanghai.cr.aliyuncs.com/ecp_builder/ackdistro:v1-22-15-ack-upgrade-lyk-test --mode upgrade
```
> support sealer upgrade

- CONTRIBUTING.md
> doc: add E2E-test doc

- build/layerutils/manifests/manifests_test.go
- docs/api/cloudrootfs.md
- pkg/image/save/save_test.go
- vendor/k8s.io/api/core/v1/generated.proto
- vendor/k8s.io/api/core/v1/types.go
- vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
- vendor/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/types.go
- vendor/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2/defaults.go
- vendor/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2/doc.go
- vendor/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2/types.go
Fixes - #2073 
Problem: Previously all of Kubernetes' image hosting has been out of gcr.io. There were significant egress costs associated with this when images were pulled from entities outside gcp. Refer to https://github.com/kubernetes/k8s.io/wiki/New-Registry-url-for-Kubernetes-(registry.k8s.io)
Solution: As highlighted at KubeCon NA 2022 k8s infra SIG update, the replacement for k8s.gcr.io which is registry.k8s.io is now ready for mainstream use and the old k8s.gcr.io has been formally deprecated and projects are requested to migrate off it. This commit migrates remaining references for kubevirt/hostpath-provisioner to registry.k8s.io.
Which issue(s) this PR fixes
Relates to umbrella issue https://github.com/kubernetes/k8s.io/issues/4780
> use new k8s registry

- cmd/sealer/cmd/image/pull.go
- pkg/clusterfile/clusterfile.go
- pkg/debug/debug.go
1. optimize the error log with the reason for failing to pull the `Seaelr Image`
2. we should expose any interface definitions including the constants we use
> chore: optimize something

- cmd/sealer/cmd/alpha/mount.go
- cmd/sealer/cmd/alpha/umount.go
- pkg/imageengine/buildah/commit.go
- pkg/imageengine/buildah/common.go
- pkg/imageengine/buildah/config.go
- pkg/imageengine/buildah/copy.go
- pkg/imageengine/buildah/images.go
- pkg/imageengine/buildah/mount.go
- pkg/imageengine/buildah/remove_container.go
fix sealer alpha mount and sealer alpha umount bug
sealer alpha mount ex:
```shell
Mount image name：
sealer alpha mount imageName
Mount image id：
sealer alpha mount ba15e47f5969
```
sealer alpha umount ex:
```shell
Umount image containerID：
sealer alpha umount ba15e47f5969
Uninstall all images:
sealer alpha umount --all
```
Fixes #2000
> fix mount and umount bug

- test/sealer_images_test.go
- test/suites/image/mount.go
add sealer alpha mount/umount e2e test
> test: add sealer alpha mount/umount e2e test

- cmd/sealer/cmd/cluster/delete.go
- cmd/sealer/cmd/cluster/run.go
- cmd/sealer/cmd/cluster/scale-up.go
- cmd/sealer/cmd/cluster/upgrade.go
- pkg/cluster-runtime/installer.go
- pkg/clusterfile/clusterfile.go
1. get container runtime should consider ClusterFile;
2. sealer clusterfile configmap name wrong.
> Fix 0.9.2 bugs

- pkg/clusterfile/decoder.go
- pkg/config/config.go
> add decode check for config

- test/sealer_build_test.go
- test/suites/build/build.go
Added method to detect multiple architectures.
Fixes #2094
> [bugfix]: fix e2e build

- cmd/sealer/cmd/alpha/gen.go
- cmd/sealer/cmd/alpha/merge.go
- cmd/sealer/cmd/alpha/mount.go
- cmd/sealer/cmd/alpha/search.go
- cmd/sealer/cmd/alpha/umount.go
- cmd/sealer/cmd/alpha/upgrade.go
- cmd/sealer/cmd/cluster/apply.go
- cmd/sealer/cmd/cluster/delete.go
- cmd/sealer/cmd/cluster/run.go
- cmd/sealer/cmd/cluster/scale-up.go
- cmd/sealer/cmd/cluster/upgrade.go
- cmd/sealer/cmd/image/build.go
- cmd/sealer/cmd/image/images.go
- cmd/sealer/cmd/image/load.go
- cmd/sealer/cmd/image/pull.go
- cmd/sealer/cmd/image/push.go
- cmd/sealer/cmd/image/save.go
- cmd/sealer/cmd/image/tag.go
- cmd/sealer/cmd/root.go
- cmd/sealer/cmd/types/types.go
replace ClusterImage to sealer image.
> [DOC]: replace ClusterImage to sealer image

- docs/api/cloudrootfs.md
- docs/api/clusterfile.md
> Add docs for customize CRI.

- cmd/sealer/cmd/cluster/run.go
- cmd/sealer/cmd/utils/application.go
- pkg/application/v2app.go
for sealer run:
```
sealer run abc:v1 --apps "" : will skip
sealer run abc:v1 --apps "fake app" : will return error
sealer run abc:v1 --apps "real app": will launch 
```
for clusterfile:  will skip launch app when appNames = [""]
```
kind: Cluster
metadata:
spec:
appNames: [""]
hosts:
- ips:
- 172.16.26.165
roles:
- master
ssh: {}
image: localhost/abc:v1
ssh:
passwd: aaaaaa
port: "22"
user: root
```
> skip run app via clusterfile Or run CLI

- .github/workflows/e2e-test-apply.yml
- .github/workflows/e2e-test-build.yml
- .github/workflows/e2e-test-image.yml
- .github/workflows/e2e-test-run.yml
- CONTRIBUTING.md
fix get secret none because pull_request event can't get github SECERT, this will cause sealer login failed.
> fix get secret none

- cmd/sealer/cmd/cluster/apply.go
- cmd/sealer/cmd/cluster/run.go
- cmd/sealer/cmd/cluster/upgrade.go
- pkg/imageengine/buildah/inspect.go
Fix the following two issues:
1. apply with mode `loadImage` will also launch the app
2. apply with no node scale will launch the apps  and do not distribute the image rootfs
> bugfix: fix apply

- pkg/registry/local.go
```
server = "default-registry.com:5000"
[host."default-registry.com:5000"]
ca = "/etc/abc.key"
```
> bugfix: fix hosts.toml format

- cmd/sealer/cmd/alpha/gen.go
- cmd/sealer/cmd/alpha/upgrade.go
- cmd/sealer/cmd/cluster/join.go
- cmd/sealer/cmd/cluster/run.go
- cmd/sealer/cmd/cluster/scale-up.go
- cmd/sealer/cmd/image/build.go
- cmd/sealer/cmd/image/pull.go
- cmd/sealer/cmd/image/push.go
- cmd/sealer/cmd/image/rmi.go
- cmd/sealer/cmd/image/save.go
- cmd/sealer/cmd/image/tag.go
Use single quotes around the password to ensure that the password is treated as a string.
example:
```shell
sealer run docker.io/sealerio/kubernetes:v1.22.15 -m 172.16.130.20 -n 172.16.130.21 -p 'Sealer123$abc'
```
> doc: modify the cmd help message 

- cmd/sealer/cmd/image/load.go
- pkg/define/options/options.go
- pkg/imageengine/buildah/load.go
we could support set tmp dir for load image. In this way, it is possible to separate the temporary directory from the system disk
Example as below :
`sealer load -i myimage.tar --tmp-dir /my/tmp/disk`
> support set tmp dir for load image

- pkg/config/pre_process_test.go
Regarding test coverage, we should un-comment those tests which we commented on during development to ensure we have good quality of code
NONE
by using base64 package to encode the exact string
run test please.
Signed-off-by: amirrmonfared <amir.monfared@ginbits.com>
> Add `NewProcessorsAndRun` test

- pkg/application/v2app.go
Kuebfile:
```
FROM scratch
APP app1 local://app1.yaml
APP app2 local://app2.yaml
APP app3 local://app3.yaml
LAUNCH ["app1","app2"]
```
```yaml
kind: Cluster
metadata:
spec:
hosts:
- ips:
- 172.16.26.168
roles:
- master
ssh: {}
image: myapp:v1
appNames: ["app3"]
ssh:
passwd: xxxx
port: "22"
user: root
status: {}
```
Fixes #2166
> bugfix: use registered app name as final app name list

- pkg/env/env.go
`os.OpenFile(strings.TrimSuffix(path, templateSuffix), os.O_CREATE|os.O_RDWR, os.ModePerm)`
if file is exits, without O_TRUNC mod, will leads to uncontrollable results. so we do better use `os.Create` to write rendered file.
> bugfix: use os.Create to write env rendered file

- pkg/clusterfile/decoder.go
- pkg/container-runtime/default.go
- pkg/container-runtime/installer.go
- pkg/env/env.go
- pkg/env/env_test.go
- pkg/infradriver/infradriver.go
- pkg/infradriver/ssh_infradriver.go
- pkg/infradriver/ssh_infradriver_test.go
- pkg/registry/local.go
- pkg/runtime/kubernetes/init.go
- pkg/runtime/kubernetes/runtime.go
- pkg/runtime/kubernetes/utils.go
- utils/ssh/ssh.go
- utils/ssh/sshcmd.go
- utils/strings/strings.go
- utils/strings/strings_test.go
```
[root@iZbp133pwc8drrt7ra1mkhZ ~]# cat .sealer/Clusterfile 
kind: Cluster
metadata:
spec:
containerRuntime: {}
env:
- RegistryDomain=sea.hub
- RegistryPort=5000
- RegistryURL=sea.hub:5000
```
when dealing with `cluster.env` , convert string slice to map `map[string]string` instead of `map[string]interface{}`.
also, reslove value overwritten problem.
Fixes #2174
> fix env bug

- cmd/sealer/cmd/cluster/upgrade.go
- pkg/cluster-runtime/installer.go
- pkg/registry/configurator.go
- pkg/registry/external.go
- pkg/registry/local.go
#2056 
dump localRegistry to configMap
ha == true:
```shell
apiVersion: v1
data:
registry: |
external: null
local:
localregistry:
registryconfig:
domain: sea.hub
port: 5000
username: ""
password: ""
ha: true
insecure: false
cert:
subjectaltname: null
deployhosts:
- 172.16.130.23
- 172.16.130.24
- 172.16.130.25
vip: 10.103.97.2
kind: ConfigMap
metadata:
creationTimestamp: "2023-04-10T02:43:55Z"
name: sealer-registry
namespace: kube-system
resourceVersion: "758"
uid: e7fc155e-cc73-4894-959b-a628e8c3f5e1
```
ha == false:
```shell
apiVersion: v1
data:
registry: |
external: null
local:
localregistry:
registryconfig:
domain: sea.hub
port: 5000
username: ""
password: ""
ha: false
insecure: false
cert:
subjectaltname: null
deployhosts:
- 172.16.130.23
vip: ""
kind: ConfigMap
metadata: …
```
> feature: dump localRegistry to cluster

- cmd/sealer/cmd/cluster/upgrade.go
- cmd/sealer/cmd/types/types.go
support using --apps in upgrade command
NONE
> support apps flag in upgrade

- cmd/sealer/cmd/image/save.go
- pkg/define/options/options.go
- pkg/imageengine/buildah/save.go
support save flags `--tmp-dir`:
`sealer save abc:v1 -o my.tar --tmp-dir /root/my-tmp`
> add save flags

- pkg/application/files.go
- pkg/application/v2app.go
- pkg/infradriver/ssh_infradriver.go
- types/api/v2/application_types.go
- utils/maps/maps.go
- utils/maps/maps_test.go
1. add  `ApplicationConfig.Env` for supporting app env render.
2. move out all app files modifying func to file.go
Clusterfile:
```yaml
kind: Cluster
metadata:
spec:
hosts:
- ips:
- 172.16.26.165
roles:
- master
image: localhost/abc:v1
ssh:
passwd: Seadent123
port: "22"
user: root
status: {}
---
kind: Application
metadata:
name: my-apps
spec:
launchApps:
- shell
- yamlapp
configs:
- name: yamlapp
env:
- gk2=testvalue
- imageName=new-image-name-for-render
- k2=v2
- name: shell
files:
- path: rediscert
strategy: "overwrite"
data: |
redis-user: root
redis-passwd: xxx
```
> feat: support env rendering for files in application/apps 

- build/kubefile/parser/image_engine_test.go
- cmd/sealer/cmd/alpha/manifest.go
- pkg/define/options/options.go
- pkg/imageengine/buildah/load.go
- pkg/imageengine/buildah/manifest.go
- pkg/imageengine/buildah/save.go
- pkg/imageengine/interface.go
1. support pack different arch image together
`sealer alpha manifest add amd:v1 arm:v1 -t all-in-one:v1`
`-t flag` : specify the wanted new image name, if null, will create a new one. if not null, it must be an existed manifest name.
`args`: if it is a single image just add it ,if it is a manifest will add it’s s all instance no matter what platform it is.
2. support save each manifest instance no-matter what platform it is.
Fixes #2180
> feat: support pack different arch image together

- pkg/cluster-runtime/scale.go
- pkg/cluster-runtime/uninstall.go
- pkg/cluster-runtime/utils.go
- pkg/registry/local.go
scale-up/delete new node will not depend on all existing nodes reachable.
Fixes #1998
> optimize scale-up and delete node

- pkg/clusterfile/clusterfile_test.go
- pkg/clusterfile/decoder.go
- pkg/clusterfile/decoder_test.go
- pkg/imageengine/buildah/save.go
- pkg/infradriver/ssh_infradriver.go
- types/api/v2/cluster_types.go
feat: support to set sealer rootfs dir via `v2.cluster.spec.DataRoot` , if not set will use `/var/lib/sealer/data` as default value. 
```yaml
kind: Cluster
metadata:
spec:
dataRoot: /tmp/kaka
hosts:
- ips:
- 172.25.146.174
roles:
- master
ssh: {}
image: docker.io/sealerio/kubernetes:v1-22-15-sealerio-2
ssh:
passwd: xxxxx
port: "22"
user: root
status: {}
```
> feat: support to set sealer rootfs dir

- cmd/sealer/cmd/image/build.go
- pkg/define/options/options.go
In some case, some applications do not need to store additional container images. it is faster and smaller.
so, at build stage, sealer could try to skip download container image through build mode option.
if it is `lite`,  will skip download container image. default value is `all`, means download all container image.
how to use: 
```
sealer build -t abc:v1 --build-mode=lite
sealer build -t abc:v1 --build-mode=lite --platform linux/arm64
sealer build -t abc:v1 --build-mode=lite --platform linux/amd64,linux/arm64
```
> feat: sealer build supports lite mode option

- cmd/sealer/cmd/image/build.go
- pkg/image/save/save.go
- pkg/imagedistributor/scp_distributor.go
1. add platform to container image list;
2. skip download duplicate container image;
3. add some debug logs
> bugfix: add platform value to container image list 

- .golangci.yml
- pkg/checker/node_checker.go
- pkg/checker/pod_checker.go
- pkg/infra/aliyun/ali_ecs.go
- pkg/infra/container/container.go
- pkg/infradriver/ssh_infradriver.go
- test/testhelper/utils.go
- utils/archive/compress.go
- utils/ssh/ssh.go
- utils/yaml/yaml.go
1. ignore `has no field or method` error from `typecheck` linter
2. replace deprecated linter to suggested replaced linter
3. fix gosec error
> chore: fix golang ci lint error

- .github/workflows/go.yml
- .golangci.yml
- pkg/imageengine/buildah/inspect.go
- Bumped the version of `golangci-lint` to `1.44.0` (this version uses far less memory than previous versions)
- Fixed one line of error message that cannot pass new lints
> Bumped the version of golangci-lint
