sealerio/sealer

.golangci.yml
=> add golang ci lint

docs/README_zh.md
Signed-off-by: oldthreefeng <louisehong4168@gmail.com>
fix docs todo list 
NONE
NONE
NONE
=> docs: fix todo list

.gitignore, Makefile, hack/build.sh, sealer/cmd/version.go, seautil/cmd/version.go, version/base.go, version/types.go, version/version.go
=> feature(main): add version

image/util.go
=> fix(main): import package error

image/base_image_manager.go, seautil/cmd/build.go
=> fix(main): fix push http registry

.github/workflows/go.yml, .github/workflows/release.yml, .golangci.yml, image/store/layer.go, image/store/layer_store.go
=> lint(main): open lint configure

runtime/init.go
Signed-off-by: oldthreefeng <louisehong4168@gmail.com>
some bugs
=> fix an upstream error, get TokenCaCertHash value error

image/base_image_manager.go, image/default_image.go, image/store/layer.go, image/store/layer_interface.go, utils/compress/compress.go
this PR fix problem of pull/push operation, where value layer would accross goroutines, which will result in sharing same layer file among all layers. Eventually, push is successed, but pull will fail
make layer to be local variable to fix this problem. Because progress func Action will run in goroutines, meanwhile Action relys on layer.
=> layer value across goroutine when pull/push, which cause some problem

CONTRIBUTIONG.md
This PR adds contributing guidance for sealer. It includes four parts:
* [Reporting security issues]
* [Reporting general issues]
* [Code and doc contribution]
* [Engage to help anything]
this is one part of https://github.com/alibaba/sealer/issues/72
none
none
none
=> docs: add contributing guidance for sealer

apply/cloud_applier.go, sealer/cmd/build.go, sealer/cmd/delete.go, sealer/cmd/list.go, sealer/cmd/login.go, sealer/cmd/pull.go, sealer/cmd/push.go, sealer/cmd/rmi.go, sealer/cmd/run.go, sealer/cmd/tag.go, sealer/cmd/version.go
fix cobra cmd;fix delete clusterFile
=> fix delete clusterFile

go.mod, image/base_image_manager.go, vendor/modules.txt
=> fix(main): fix logger

filesystem/filesystem.go
support diffient  rootfs struct,we need fixed init.sh is ok.
=> fix(main): filesystem fix to rootfs support ,not fixed is docker dir

common/common.go, image/util.go, runtime/init.go, runtime/kubeadm.go, runtime/masters.go, runtime/nodes.go, runtime/runtime.go, runtime/template.go
=> fix(main): fix loading metadata

apply/cloud_applier.go, guest/guest.go, parser/parser.go
Optimize/parse kubefile log and fix umount /tmp/cluster Dir
=> Optimize/parse kubefile log and fix umount /tmp/cluster Dir

CONTRIBUTIONG.md
=> optimize: improve contribution doc, supplement the part of rebase

logger/conn.go, logger/console.go, logger/file.go, logger/file_test.go, logger/log.go
=> fix: print log err to stderr instead of stdout

Makefile, image/distributionutil/registry.go, image/util.go
=> fix: pull image failed when auth is empty

parser/parser.go
Ignore kubefile comments,
Comment lines do not require warning　
Fixes #76 
If the line starts with #,ignore
=> ignore kubefile comments

logger/config.go, logger/log.go, sealer/cmd/root.go
Fixes #56 
add a flag long: "debug", short: "d". 
run sealer ... -d to make logger.Debug work, print debug message.
=> optimize: add debug mode

registry/layer.go, utils/compress/compress.go
=> optimize: verify layer digest when push the layer

docs/api/cloudrootfs.md
=> docs(main): fix rootfs docs

README.md
=> docs(main): rename CONTRIBUTIONG.md to CONTRIBUTING.md

apply/default_applier.go, runtime/masters.go, runtime/nodes.go, runtime/registry.go, runtime/reset.go, runtime/runtime.go
=> feat(main): clean feature #81 no.4

.github/workflows/label.yml
=> e2e-test label Bot

apply/apply.go, apply/cloud_applier.go, apply/default_applier.go
=> feat(main): saveClusterfile extends #81 no.1

apply/default_applier.go, apply/run.go
=> feat(main): run  node bug extends #81 no.2

runtime/init.go, runtime/runtime.go
=> feat(main): fix metadata not found

apply/default_applier.go, runtime/cni.go, runtime/runtime.go
=> feat(main): cni feature #81 no.5

apply/run.go
feature:  support ssh port
Fixes #121
=> support ssh port

docs/design/global-config.md, docs/design/global-config_zh.md
For application configuration.
=> The CloudImage global config design

apply/run.go, common/structs.go, sealer/cmd/run.go
=> sealer run support --interface #143

apply/default_applier.go, filesystem/filesystem.go, filesystem/filesystem_test.go, guest/guest.go
=> feat(main): umount feature #81 no.6

apply/default_applier.go
=> bugfix: fix a misspelling

apply/run.go, common/structs.go, sealer/cmd/run.go
`sealer run --svccidr x.x.x.x/x ...`
Fixes #173
sealer run support svccidr
=> Add svccidr support

utils/ssh/scp.go
Sealer apply will copy the files to remote host even if that file already exists because there is no checking process before copy. The new copy function will first check if the remote file exists and if it exists, it will check the md5sum of that remote file and compare it with local file's md5sum value. The copying process only happens when remote file does not exist or is stale.
Fixes #164
=> fix sealer apply repeatedly copying remote existing files

image/distributionutil/push.go
=> clean compress file after uploading

infra/aliyun/ali_ecs.go
=> fix get instances ip bug

docs/README_zh.md
Find some Chinese typo when I am reading the Readme doc.
=> Fix some Chinese typo

runtime/init.go, runtime/masters.go
=> fix(main): ln error

.github/workflows/go.yml, .github/workflows/release.yml
=> fix(main): action yaml fix

README.md, docs/README_zh.md
Increase the readability of documents
No
Added a comment in the configuration example of Clusterfile in the README.md file.
Explains how to use ssh configuration
=> Add comments to the Clusterfile

.github/workflows/auto-invite.yml, .github/workflows/e2e-test.yml
=> Update e2e-test.yml for test

.github/workflows/auto-invite.yml, .github/workflows/e2e-test.yml
if comment body on this pr contains '/test' will trigger this flow.
=> feature:add sealer e2e workflow using PR comment 

logger/log.go
=> turn on log option usePath to print file:line info in log header

.github/workflows/release.yml, Makefile, hack/build.sh
=> fix(main): fix build shell version

test/sealer_build_test.go, test/suites/apply/apply.go, test/testhelper/settings/common.go, test/testhelper/utils.go
Adding E2E test for sealer build to keep our code more robust
1, add local build test ,with only copy and all build instructs
2, add cloud build test with all build instructs
3, add abnormal build scenario expected error
install ginkgo and config your env as readme.md said.
ginkgo -v --focus="sealer build" test
=> feature: add E2E test for sealer build 

build/cloud_builder.go, build/local_builder.go
no need to push images when build type is cloud at onlycopy scenario
delete push code
=> bugfix:no need to push images when build type is cloud at onlycopy scenario

.github/workflows/e2e-test.yml, test/suites/apply/apply.go, test/suites/build/fixtures/cloud_build/Kubefile, test/suites/build/fixtures/local_build/Kubefile, test/suites/registry/registry.go, test/testhelper/utils.go
Adding E2E test for sealer build to keep our code more robust
1,checkout PR HEAD commit for e2e test 
2,use testhelper utils
install ginkgo and config your env as readme.md said.
ginkgo -v --focus="sealer build" test
=> feature: add E2E test for sealer build

image/default_image.go, image/image.go, image/utils/meta_image.go, sealer/cmd/rmi.go
=> rmi by image id

image/default_image_metadata.go, image/utils/error.go, image/utils/meta_image.go
=> support tag sealer image with id

image/default_image.go, image/reference/reference.go, sealer/cmd/push.go, utils/file.go
=> avoid file close many times

runtime/reset.go
fix delete failure after master0 execution
#263 
The CleanFS method will do this
=> Fix delete failure after master0 execution

runtime/init.go
=> feat: #182 auto detect network interface name by master ip

test/sealer_images_test.go, test/suites/image/image.go, utils/ssh/scp.go
1. feature: add E2E test for sealer images
2. fix iplist number different from count
=> feature: add E2E test for sealer images

apply/run.go, sealer/cmd/run.go
=> bugfix:--interface not work #227  &&  --podcidr and --svccidr may not work

test/README.md, test/sealer_apply_test.go
Adding sealer apply test to keep our code more robust
1,include  init, scale up, scale down and clean up cluster at ali cloud mode
2,include  init, scale up, scale down and clean up cluster at bare metal mode
install ginkgo and config your env as readme.md said.
example:  if you want to test sealer build , you can run below cmd.
ginkgo -v --focus="sealer apply" test
need to fix issue #288 #291 first
=> feature: add sealer apply test case

test/sealer_images_test.go, test/suites/image/image.go, test/testhelper/settings/common.go, utils/ssh/scp.go
=> optimize image e2e test

filesystem/filesystem.go, runtime/reset.go
Fix umount failure affecting apply
Delete $home/.sealer/Cluster at the end
fix #314
=> optimize dir busy umount image

.github/workflows/e2e-test.yml, test/sealer_apply_test.go, test/sealer_run_test.go, test/suites/apply/apply.go, test/testhelper/settings/common.go, test/testhelper/utils.go
Adding sealer apply test to keep our code more robust
1,fix: check out PR latest commit hash.
2,fix: github action machine is diffrent with local vm while using sudo cmd . use runner home path.
install ginkgo and config your env as readme.md said.
example:  if you want to test sealer build , you can run below cmd.
ginkgo -v --focus="sealer apply" test
=> fix: E2E test for sealer apply

filesystem/filesystem.go
=> fix umountImage log

build/local_builder.go, parser/parser.go, test/sealer_build_test.go
refactor:
1, return fast if decode kubefile line failed;
2, modify build test case;
3, umount tmpdir if build failed;
=> refactor:build test case and local build steps

test/sealer_images_test.go, test/sealer_login_test.go, test/suites/image/image.go
=> add login and image list test

build/cloud_builder.go, build/context.go, build/run_build_commands.go
fix:
1，delete temp file when cloud build failed
link to issue #328
=> fix:delete temp file when cloud build failed

image/store/filesystem.go, image/store/layer.go
=> optimize: assemble in-memory

sealer/cmd/delete.go
when use sealer delete . Its a dangerous comand. it should be twice interacition with user.
=> feature: add twice interacition when sealer delete

image/default_image_file.go, image/store/layer.go, image/store/layer_store.go, utils/archive/compress.go, utils/archive/compress_test.go
=> optimize: compress with buffer

build/cloud_builder.go, build/local_builder.go, test/sealer_build_test.go
1, add pull image at local build due to image metadata chanaged
2, optmize cloud build 
3, set max waite time for build e2e test, in order to adapt run time to github network
test report : https://github.com/kakaZhou719/sealer/runs/2882558926?check_suite_focus=true
=> fix:add pull image at local build

infra/aliyun/ali_ecs.go, utils/ssh/ssh.go
set default user cpu memory
#351
=> set default user cpu memory

build/local_builder.go, common/common.go, image/default_image.go, image/store/image.go, image/store/layer_store.go, image/util.go, image/utils/meta_image.go, parser/parser.go, parser/parser_test.go, types/api/v1/image_types.go, utils/archive/compress.go, utils/file.go
save every image.yaml into /var/lib/sealer/metadata/imagedb.
remove the image name during building.
add platform, and sealer_version for image.
=> optimize image structure

runtime/reset.go, test/suites/apply/apply.go
1.fix reset master failed when it was executed asynchronously
2.add sealer delete --force for e2e test
#288
=> fix reset master failed when it was executed asynchronously 

build/context.go, build/local_builder.go, build/run_build_commands.go, common/common.go, sealer/cmd/build.go, test/suites/build/build.go
1, add context path at local build
2, delete -c flag on build cmd
test report
https://github.com/alibaba/sealer/runs/2938256523?check_suite_focus=true
link to issue #353
=> fix:add build context

build/cloud_builder.go, build/local_builder.go, build/run_build_commands.go, check/checker/registry_checker.go, check/checker/types.go, check/service/pre_check.go
feature:
1, add prechecker 
2，check registry auth info before run cloud build
=> feat:check registry login status

.github/workflows/e2e-test.yml
add workflow trigger
test report https://github.com/bxy4543/sealer/runs/2951742391?check_suite_focus=true
=> add workflow trigger

test/sealer_apply_test.go
delete e2e only run apply test
=> delete e2e only run apply test

common/common.go, image/store/const.go, image/store/layer_store.go, image/store/utils.go, sealer/boot/boot.go, sealer/main.go
There is a new package named onstart, we can do some initialization job within the package.
=> optimize: do layer filesystem initialization on start

apply/apply.go, apply/cloud_applier.go, apply/default_applier.go, sealer/cmd/apply.go, sealer/cmd/delete.go, seautil/cmd/apply.go
fix sealer delete panic when the file does not exist
fix #255
=> fix sealer delete panic when the file does not exist

README.md, docs/README_zh.md
=> update doc version

runtime/template.go
=> fix(main): fix proxy ipvs model

common/common.go
=> sort out const

.github/workflows/e2e-test.yml, README.md, docs/README_zh.md, release_note.md, test/README.md
add release-v0.2.1
test report ：https://github.com/alibaba/sealer/runs/2960516320?check_suite_focus=true
=> add release-v0.2.1

apply/run.go
=> sort import

check/checker/node_checker.go, check/checker/pod_checker.go, check/checker/svc_checker.go, common/std.go, image/default_image.go, logger/conn.go, logger/console.go, logger/file.go, logger/log.go, sealer/cmd/images.go, utils/exec.go, utils/ssh/scp.go
I guess it might lost some log info if we print to different stdout concurrently.
=> optimize: unify std out err

build/context.go, build/local_builder.go, image/cache/cache.go, image/cache/chain.go
image id is generated from digest(image yaml).Hex()
=> feature: set unique image id

apply/default_applier.go, filesystem/filesystem.go, runtime/registry.go, utils/iputils.go, utils/ssh/connect.go, utils/ssh/scp.go, utils/strings.go
=> Fix the problem that IP contains ports, and support setting non default ports for SSH and registry.

build/cloud_builder.go
=> reformat the order of imports

build/local_builder.go, utils/ssh/ssh.go
optimize some build error logs     #407 
Reduced retry ping time  #406
=> Optimize some build error logs and Reduced retry ping time

utils/ssh/connect.go, utils/ssh/sshcmd.go
=> close ssh client

build/local_builder.go
fix the error caused by modifying the log
=> fix the error caused by modifying the log

docs/user-guide/get-started.md
=> mispronounced

config/config.go, runtime/registry.go
=> Fix can't get regsitry configuration

image/utils/meta_image.go, sealer/cmd/completion.go, sealer/cmd/push.go, sealer/cmd/rmi.go
=> add cobra auto completion

filesystem/rootfs/docker/etc/daemon.json, filesystem/rootfs/docker/etc/docker.service, filesystem/rootfs/docker/scripts/clean.sh, filesystem/rootfs/docker/scripts/docker.sh, filesystem/rootfs/docker/scripts/init-registry.sh, filesystem/rootfs/docker/scripts/init.sh, filesystem/rootfs/rootfs/Kubefile, filesystem/rootfs/rootfs/etc/10-kubeadm.conf, filesystem/rootfs/rootfs/etc/kubelet.service, filesystem/rootfs/rootfs/scripts/init-kube.sh, filesystem/rootfs/rootfs/scripts/kubelet-pre-start.sh, filesystem/rootfs/rootfs/statics/audit-policy.yml
=> fix(main): add rootfs struct

apply/apply.go, apply/cloud_applier.go, apply/default_applier.go, apply/run.go, infra/aliyun/ali_provider.go, utils/docker_config.go, utils/yaml.go
Save the cluster file after each step of reconcile resources
delete interface arg
=> Optimize save clusterfile

build/lite_builder.go
=> Fix if build image name without tag

build/local_builder.go, runtime/kubeadm.go
using English comment;
sort import
=> Fix issue:Train NO.1 simple PR quick start #437

build/lite_builder.go, filesystem/filesystem.go
=> the image cache is added to the cluster image layer and the cleaning

build/lite_builder.go, filesystem/filesystem.go
=> fix the bug that cannot be added to the image layer

filesystem/rootfs/docker/scripts/clean-docker.sh, filesystem/rootfs/docker/scripts/clean.sh, filesystem/rootfs/docker/scripts/docker.sh, filesystem/rootfs/rootfs/etc/Clusterfile, filesystem/rootfs/rootfs/scripts/clean-kube.sh
=> fix(main): fix rootfs struct spilt clean shell

README.md, docs/README_zh.md, release_note.md, test/README.md
=> add v0.3.0 release note

runtime/init.go
Modify return err details in #437
=> Modify return err details

build/context.go
Signed-off-by: liutao <tao_liu@ruijie.com.cn>
Fix the returned error details,This error is located in https://github.com/alibaba/sealer/blob/main/build/context.go#L54
=> return more error detail log.

plugin/plugin.go
=> add plugin interface

go.mod, go.sum, image/distributionutil/pull.go, image/distributionutil/push.go, vendor/golang.org/x/sync/AUTHORS, vendor/golang.org/x/sync/CONTRIBUTORS, vendor/golang.org/x/sync/LICENSE, vendor/golang.org/x/sync/PATENTS, vendor/golang.org/x/sync/errgroup/errgroup.go, vendor/modules.txt
fix: <-compressChan block the defer func, but this is useless channel.
and use errgroup to take place of errChan
=> fix: chan block defer return

command/command.go, infra/container/provider_client.go, utils/exec.go
1. optimize build log err :  exe
2. fix :
=> optimize build log

runtime/kubeadm.go
=> add English comment

build/local_builder.go
=> fix the exception of executing kubectl or helm command during lite build

filesystem/filesystem.go, runtime/registry.go, utils/iputils.go, utils/ssh/scp.go, utils/ssh/ssh.go, utils/ssh/sshcmd_test.go
fix is local host and optimize ssh utils
=> fix is local host and optimize ssh utils

docs/build/build_zh.md
=> update build doc

build/build_mount.go, build/cloud_builder.go, build/const.go, build/context.go, build/instruction_handler.go, build/local_builder.go, build/utils.go, client/docker_client.go, common/common.go, infra/container/provider_client.go
1,optimize build code:check build args such as: context and kubefile .make them as abs path.
2,optimize build code: split common code to utils.go
3, optimize build code: split build mount code to build_mount.go, support to add default target and upper.
=> optimize build code

build/build_mount.go, build/const.go, build/local_builder.go, build/utils.go, runtime/init.go, runtime/registry.go, runtime/runtime.go
cache docker images while run build.
save docker images as a cluster image layer , which type is BASE and value is sha hash.
when start docker registry ,will merge and mount this base layer and rootfs regsitry first. when build k8s app , the upper dir will cache docker images and save it with cluster image.
=> Feature: cache docker image for build

build/build_mount.go, build/utils.go, filesystem/filesystem.go, utils/mount/overlay2.go
=> fix mount layer sequence

build/cloud_builder.go
=> local build needn't login

Makefile, logger/config.go, logger/conn.go, logger/conn_test.go, logger/console.go, logger/console_test.go, logger/file.go, logger/file_test.go, logger/log.go, logger/log_test.go
=> fix(docs): add  lic docs

.github/workflows/go.yml, Makefile
=> fix(main): add actions lic

README.md, apply/default_applier.go, build/instruction_handler.go, build/utils.go, docs/README_zh.md, plugin/plugins.go, release_note.md, runtime/registry.go, test/README.md, utils/mount/default.go, utils/mount/overlay2.go, utils/strings.go
=> Release v0.3.3

infra/infra.go, plugin/shell_plugin.go, utils/ssh/ssh.go
=> add plugin exec dir

infra/container/container.go
=> fix:fix panic when run container build if container network is not exist

apply/cloud_applier.go, config/config.go, config/config_test.go, plugin/plugins.go, plugin/plugins_test.go, runtime/registry.go, runtime/utils.go, utils/mount/overlay2.go, utils/ssh/scp.go, utils/ssh/sshcmd.go
fix plugin not working in cloud apply
fix failed to umount $rootfs/registry cause the sealer delete failure
=> fix plugin not working in cloud apply

Makefile
Makefile添加help & 代码格式化
Signed-off-by: ysicing <i@ysicing.me>
=> docs(makefile): makefile add help func & code style func

apply/apply.go, apply/cloud_applier.go, common/common.go, config/config.go, plugin/plugins.go, utils/file.go
optimize decode Cluster from clusterfile
=> optimize get cluster from file

plugin/hostname_plugin.go, plugin/hostname_plugin_test.go, plugin/plugins.go
…e through the hostname plugin data
=> feature[plugin]: add the hostname plugin,which can change the hostname through the hostname plugin data

.github/workflows/go.yml, Makefile
fix macOS make license
Signed-off-by: ysicing <i@ysicing.me>
=> fix(#549): fix macOS make license

README.md, docs/README_zh.md, release_note.md, test/README.md
=> add release v0.4.0

apply/default_applier.go, apply/run.go, apply/run_test.go, docs/design/plugin.md, plugin/shell_plugin.go, utils/iputils.go
shell plugin support on field. #551
=> shell plugin support on field. #551

common/common.go, logger/log.go, sealer/boot/boot.go, sealer/cmd/root.go
The default log file is /root/.sealer.json or something else?
#464
=> add default log config

docs/README_zh.md
=> correct one wrongly written

applications/cassandra/Kubefile, applications/cassandra/README.md, applications/cassandra/cassandra-manifest.yaml, applications/cockroachdb/Kubefile, applications/cockroachdb/README.md, applications/cockroachdb/cockroachdb-manifest.yaml, applications/mongodb/Kubefile, applications/mongodb/README.md, applications/mongodb/mongodb-manifest.yaml, applications/mysql/Kubefile, applications/mysql/README.md, applications/mysql/mysql-manifest.yaml, applications/postgresql/Kubefile, applications/postgresql/README.md, applications/postgresql/postgresql-manifest.yaml, applications/redis/Kubefile, applications/redis/README.md, applications/redis/redis-manifest.yaml, applications/tidb/Kubefile, applications/tidb/README.md, applications/tidb/tidb/crd.yaml, applications/tidb/tidb/manifest.yaml, applications/tidb/tidb/operator.yaml
=> [sealer-app-images] add database images

.github/workflows/e2e-test-apply.yml, .github/workflows/e2e-test-build.yml, .github/workflows/e2e-test-image.yml, .github/workflows/e2e-test-run.yml, build/lite_builder.go
fix Lite Build not saving cached images because sea.hub is not in hosts
=> fixed lite Build not having cached images

.github/workflows/markdownlint.yml
add markdownlint action for sealer
just see it in github ci actions
none
=> chore: add markdownlint action for sealer

.github/workflows/markdownlint.yml
In workflow actions, docker://avto-dev/markdown-lint@v1.5.0 is not correct. It should be docker://avto-dev/markdown-lint:v1.5.0
none
none
none
none
=> fix markdownlint image format

.github/workflows/markdownlint.yml
change markdownlint image org from avto-dev to avtodev
the doc in https://github.com/marketplace/actions/markdown-linting-action contains some mistakes.
=> change markdownlint image org from avto-dev to avtodev

.github/workflows/misspell.yml, applications/openebs/cstor/cstor-operator.yaml, applications/openebs/jiva/jiva-operator.yaml, applications/redis/redis-manifest.yaml, docs/user-guide/get-started.md
add misspell check and fix existing typos
none
none
none
none
=> action: add misspell check and fix existing typos

utils/mount/empty_interface_overlay2.go
=> add empty interface, avoid golangci lint exception prompt under macox

build/build_mount.go, filesystem/filesystem.go, runtime/init.go, runtime/registry.go, utils/file.go
fix apply to cause registry not found layer dir
fix #542
=> fix apply to cause registry not found layer dir

applications/README.md, applications/cassandra/Kubefile, applications/cassandra/README.md, applications/cassandra/cassandra-manifest.yaml, applications/cockroachdb/Kubefile, applications/cockroachdb/README.md, applications/cockroachdb/cockroachdb-manifest.yaml, applications/ingress/ingress-nginx-manifest.yaml, applications/kafka/manifest.yaml, applications/minio/Kubefile, applications/minio/README.md, applications/minio/minio-manifest.yaml, applications/mongodb/mongodb-manifest.yaml, applications/mysql/mysql-manifest.yaml, applications/postgresql/Kubefile, applications/postgresql/README.md, applications/postgresql/postgresql-manifest.yaml, applications/prometheus-stack/Kubefile, applications/prometheus-stack/README.md, applications/prometheus-stack/examples/Clusterfile.yaml, applications/prometheus-stack/prometheus/operator.yaml, applications/redis/redis-manifest.yaml, applications/tidb/Kubefile, applications/tidb/README.md, applications/tidb/tidb/manifest.yaml, applications/zookeeper/manifest.yaml
For optimal performance , deploy some apps  with OpenEBS Local PV. 
For replicated storage features ,deploy some apps with OpenEBS Jiva. 
openebs jiva:
* registry.cn-qingdao.aliyuncs.com/sealer-apps/mysql:8.0.26 
* registry.cn-qingdao.aliyuncs.com/sealer-apps/redis:6.2.5
* registry.cn-qingdao.aliyuncs.com/sealer-apps/mongodb:4.4.8
openebs localpv:
* registry.cn-qingdao.aliyuncs.com/sealer-apps/minio:2021.6.17  
* registry.cn-qingdao.aliyuncs.com/sealer-apps/postgresql:11.12.0 
* registry.cn-qingdao.aliyuncs.com/sealer-apps/cassandra:4.0.0
* registry.cn-qingdao.aliyuncs.com/sealer-apps/tidb:v1.2.1
* registry.cn-qingdao.aliyuncs.com/sealer-apps/cockroach:v21.1.7
* registry.cn-qingdao.aliyuncs.com/sealer-apps/kafka:2.8.0
* registry.cn-qingdao.aliyuncs.com/sealer-apps/zookeeper:3.7.0
* …
=> change some apps storageClass from jiva to localpv

build/lite_builder.go, build/local_builder.go, common/common.go, filesystem/filesystem.go, utils/file.go, utils/mount/overlay2.go
=> optimize the lite build step

applications/yrcloudfile/README.md
=> bugfix: add https to website address

test/sealer_apply_test.go, test/suites/apply/apply.go, utils/file.go
optimize e2e apply executes machine is not master0 test
=> optimize e2e apply test

utils/ssh/connect.go
just optimize some base code. Remove the unnecessary os.Exit(1) in the business no related code.
=> remove unnecessary underlying func wrap

image/default_image_file.go, image/default_image_metadata.go, image/store/filesystem.go, image/store/image_interface.go, image/store/image_store.go, image/store/image_store_test.go, image/types/Image_metadata.go, sealer/cmd/images.go, utils/file.go
show Image creation time and size.
=> show more image details

Adopters.md, README.md
complete adopter markdown for sealer project:
* Alibaba Cloud
* Zhengcaiyun
* Mingyuanyun
* Harmony Cloud
none
none
none
none
=> docs: complete adopter markdown for sealer project

.golangci.yml, build/cloud_builder.go, cert/kube_certs.go, filesystem/filesystem.go, image/reference/reference.go, image/store/layer.go, image/store/layer_store.go, logger/log.go, plugin/shell_plugin.go, sealer/main.go, utils/archive/compress.go, utils/file.go, utils/mount/default.go, utils/uuid.go
add ifshort in golangci-lint
ifshort  https://github.com/esimonov/ifshort helps check if your code uses short syntax for if-statements whenever possible.
I think it is a good way to write golang code.
none
none
none
none
=> lint: add ifshort in golangci-lint

apply/cloud_applier.go, apply/current_cluster.go, apply/default_applier.go, plugin/plugin.go, plugin/shell_plugin.go
1.add shell plugin phase originally
2. fixed apply failure due to absence of K8S client during cluster initialization.
=> add shell plugin phase originally

build/lite_builder.go, build/local_builder.go, build/utils.go, utils/hosts.go
more details see issue #622
Fixes #622
check the local regsitry status whether the port 5000 can be connected.
=> fixbug: lite build cache sectional images due to registry not start

build/local_builder.go
=> Use retry instead of sleep to check if all pods are running

.golangci.yml, utils/cidr.go
Made change with .golangci.yml, is it okay? @fanux
=> chore: golang lint ci add unconvert (#609)

sealer/cmd/pull.go, sealer/cmd/rmi.go, sealer/cmd/run.go, sealer/cmd/tag.go, sealer/test/Clusterfile
Update the old image name in the example
=> Update the old image name in the example

apply/default_applier.go, build/lite/lite_builder.go, build/local/local_builder.go, common/common.go, filesystem/filesystem.go, image/distributionutil/login.go, runtime/init.go, runtime/masters.go, runtime/nodes.go, runtime/runtime.go, runtime/utils.go, test/sealer_apply_test.go, utils/ssh/connect.go, utils/ssh/ssh.go
Optimize save registry cache.
Change log file to /var/lib/sealer/log, because github action no permission to save logs when run e2e test.
=> Optimize save registry cache.

docs/site/config.toml, docs/site/content/docs/getting-started/run-kubernetes-cluster.md, docs/user-guide/get-started.md
Highlight affects view,set highlight false
=> add site run docs

docs/api/clusterfile.md, docs/contributing_zh.md, docs/debug/README.md, docs/design/global-config.md, docs/site/content/authors/_index.md, docs/site/content/docs/advanced/arch.md, docs/site/content/docs/getting-started/using-config.md, docs/user-guide/docker-image-cache.md, docs/user-guide/get-started.md
=> doc:fix typo

docs/site/content/docs/getting-started/applications.md
=> doc: add doc site applications

release_note.md
=> add release v0.5.0

docs/site/content/docs/getting-started/build-cloud-image.md
=> doc :add build site doc

applications/README.md, applications/loki-stack/fluentbit-loki-stack/Kubefile, applications/loki-stack/fluentbit-loki-stack/README.md, applications/loki-stack/fluentbit-loki-stack/examples/Clusterfile.yaml, applications/loki-stack/fluentbit-loki-stack/fluentbit-loki-stack.yaml, applications/loki-stack/promtail-loki-stack/Kubefile, applications/loki-stack/promtail-loki-stack/README.md, applications/loki-stack/promtail-loki-stack/examples/Clusterfile.yaml, applications/loki-stack/promtail-loki-stack/promtail-loki-stack.yaml
1, registry.cn-qingdao.aliyuncs.com/sealer-apps/loki-stack-promtail:v2.2.0
2, registry.cn-qingdao.aliyuncs.com/sealer-apps/loki-stack-fluentbit:v2.2.0
=> [sealer-app-images] add app images 

test/sealer_apply_test.go, test/sealer_build_test.go, test/sealer_images_test.go, test/sealer_run_test.go, test/suites/apply/apply.go, test/suites/apply/fixtures/config_plugin_for_test.yaml, test/testhelper/utils.go
add e2e tests for config and plugin.
optimize e2e test func
=> optimize e2e test

docs/site/content/docs/advanced/GPU.md
=> add gpu for sealer doc

.github/ISSUE_TEMPLATE/bug-report.md
=> chore :add more info for github action

docs/design/build_zh.md
=> doc:add build design doc

docs/site/content/docs/advanced/cloudrootfs.md, docs/site/content/docs/getting-started/build-cloud-image.md, docs/site/content/docs/reference/Kubefile.md, docs/site/content/docs/reference/clusterfile.md
add clusterfile, Kubefile docs
=> add clusterfile, Kubefile docs

docs/api/kubefile.md, docs/build/build_zh.md, docs/site/content/docs/advanced/GPU.md, docs/site/content/docs/getting-started/build-cloud-image.md, docs/site/content/docs/help/faq.md
=> doc: add faq for sealer site

docs/build/build_zh.md, sealer/cmd/build.go
=> docs:modify docs about lite build

client/k8s/client.go, plugin/shell_plugin.go
fix #795 : add the shell plugin role option
=> fix #795 : add the shell plugin role option

docs/site/src/docs/help/faq.md
=> doc:faq:add hosts config

docs/site/src/docs/help/faq.md
=> doc faq: add check cached image section

apply/default_applier.go, checker/check_list.go, checker/host_checker.go, checker/node_checker.go, sealer/cmd/check.go, utils/ssh/scp.go
add apply pre check and save the Clusterfile when check passes
gen-doc auto generate commend line doc
consider the offline environment, time sync only does check
=> feature: add apply pre check

build/buildkit/buildlayer/layer_copy.go, client/docker/images.go
optimize returns an error when build fails to pull the image from the imageList
fix #833
=> optimize returns an error when build fails to pull the image from the imageList

sealer/cmd/delete.go
optimize sealer delete trigger conditions
=> optimize sealer delete trigger conditions

docs/site/src/docs/help/faq.md
=> doc:add check list for failed cache

docs/site/src/docs/advanced/kyverno-build-in.md, docs/site/src/docs/advanced/raw-docker-cloudimage.md
this PR consist of introductions of how to build a base image with raw docker and how to build a base image with kyverno(webhook)
=> Build image docs

applications/flannel/Kubefile, applications/flannel/README.md, applications/flannel/init-kube.sh, applications/flannel/kube-flannel.yml
[sealer-app-images] add app images  flannel
=> [sealer-app-images] add app images  flannel

image/default_image.go, image/utils/meta_image.go
support rmi with partial id #265
=> support rmi with partial id

image/distributionutil/registry.go
=> fix return error

.github/workflows/release.yml, note.sh
=> Added ossurl and modified the OSS access path 

docs/site/src/.vuepress/config.js, docs/site/src/docs/advanced/kyverno-build-in.md, docs/site/src/docs/advanced/raw-docker-cloudimage.md
this PR add some contents to documents about kyverno
=> improve kyverno docs

docs/site/src/docs/advanced/dev-plugin.md, docs/site/src/docs/advanced/develop-plugin.md, docs/site/src/docs/getting-started/plugin.md
=> Doc: add golang .so plugin

filesystem/rootfs/docker/etc/docker.service, note.sh
add iptables for docker.service
=> add iptables for docker.service

runtime/init.go, utils/ssh/connect.go, utils/ssh/scp.go, utils/ssh/sshcmd.go
correct error handling, connection leak fixing, remove redundent code, etc.
=> clean code and fix remote connection leak

pkg/runtime/init.go, pkg/runtime/kubeadm.go, pkg/runtime/kubeadm_config.go, pkg/runtime/kubeadm_config_test.go, pkg/runtime/kubeadm_runtime.go, pkg/runtime/masters.go, pkg/runtime/nodes.go, pkg/runtime/runtime.go, utils/ssh/ssh.go, utils/yaml.go
1. load kubeadm config like kubeproxy config, certSANS...
2. set k.JoinToken, k.TokenCaCertHash, k.CertificateKey in kubeadm join config
3. set join master config
4. generate join node config
=> V2 runtime 

apply/applytype/local.go, image/default_image.go, pkg/runtime/init.go, pkg/runtime/masters.go, pkg/runtime/nodes.go, pkg/runtime/registry.go, runtime/init.go, runtime/masters.go, runtime/nodes.go, runtime/registry.go, sealer/cmd/delete.go, sealer/cmd/root.go, utils/clusterfile_util.go, utils/ssh/sshcmd.go, utils/utils.go
add some phase logs;
silence log in sshcmd.go;
fix bug: delete will fail if kubeadm has been deleted;
fix bug: delete will fail if sealer-registry has been deleted;
fix bug: session not closed
=> make sealer log more readable.

pkg/filesystem/README.md, pkg/filesystem/filesystem.go, pkg/filesystem/filesystem_test.go, pkg/guest/guest.go, pkg/runtime/utils.go
V2 filesystem and guest module upgrade
#873
=> V2 filesystem and guest module upgrade

client/docker/images.go, docs/design/plugin.md, docs/design/plugin_zh.md
ep: image: 'nginx:latest'
yaml image name may have quotation marks, which may cause an error when pulling the image
=> yaml image name may be in quotes,which may cause an error when pull image

plugin/cluster_check_plugin.go, plugin/etcd_backup_plugin.go, plugin/factory.go, plugin/hostname_plugin.go, plugin/labels.go, plugin/plugin.go, plugin/plugins.go, plugin/shell_plugin.go, plugin/test/label_nodes.go, plugin/test/test_clusterfile.yaml
add get plugin type to avoid type conflicts. 
we must fill in action filed at plugin.yaml  to illustrate  which phase to run.
=> add plugin type to avoid conflicts

Makefile
add gosec makefile and version is 2.2.0
see https://github.com/Ynniss/golang-security-action/blob/master/Dockerfile
=> fix(ci): add gosec makefile

pkg/checker/host_checker.go
There are some errors haven't been wrapped when upgrading checker module into cluster V2, so this Pr wraps those errors
=> wrap errors in checker

docs/site/src/docs/advanced/develop-plugin.md, plugin/plugins.go
=> doc:plugin:modify plugin type

.github/workflows/release.yml
optimization release action process
=> fix(ci): optimization ci release

infra/README.md
=> fix(ci): optimization docs clusterfile

cert/cert_cmd.go, filesystem/rootfs/docker/scripts/docker.sh, filesystem/rootfs/docker/scripts/init-registry.sh, runtime/init.go, runtime/masters.go, runtime/runtime.go
=> add registry cert

docs/design/build_zh.md
=> make design docs consistent with implement

pkg/plugin/cluster_check_plugin.go, pkg/plugin/cluster_check_plugin_test.go, pkg/plugin/etcd_backup_plugin.go, pkg/plugin/etcd_backup_plugin_test.go, pkg/plugin/factory.go, pkg/plugin/hostname_plugin.go, pkg/plugin/hostname_plugin_test.go, pkg/plugin/labels.go, pkg/plugin/labels_test.go, pkg/plugin/plugin.go, pkg/plugin/plugins.go, pkg/plugin/plugins_test.go, pkg/plugin/shell_plugin.go, pkg/plugin/shell_plugin_test.go, pkg/plugin/test/Kubefile, pkg/plugin/test/label_nodes.go, pkg/plugin/test/label_nodes.yaml, pkg/plugin/test/test_clusterfile.yaml, plugin/plugins_test.go, utils/ssh/ssh.go
=> Plugin module upgrade

image/reference/reference.go, image/reference/util.go
fix image tag cannot be uppercase.
=> fix image tag cannot be uppercase.

apply/v2/applydriver/local.go, apply/v2/processor/create.go, apply/v2/processor/upgrade.go, pkg/runtime/kubeadm_runtime.go, pkg/runtime/runtime.go
fix apply upgrade to get kubernetes version from kubeadm config instead of Metadata.
encapsulate phase exec plugin function
=> fix upgrade get k8s version

infra/aliyun/ali_provider.go, infra/aliyun/ali_vpc.go
default  InternetChargeType is PayByBandwidth fix it is PayByTraffic 
url is https://help.aliyun.com/document_detail/36016.htm?spm=a2c4g.11186623.0.0.58956cf0nTx7ZX#doc-api-Vpc-AllocateEipAddress
=> fix(infra): optimization aliyun vpc InternetChargeType=PayByTraffic

image/save/save.go, vendor/github.com/distribution/distribution/v3/registry/proxy/proxymanifeststore.go, vendor/github.com/distribution/distribution/v3/registry/proxy/proxyregistry.go
1.Image save module support pull from private registry
2.delete useless file scheduler-state.json
=> Image save module improvement

apply/v2/applydriver/local.go, apply/v2/applydriver/utils.go, apply/v2/processor/delete.go, apply/v2/processor/interface.go, apply/v2/processor/scale.go, apply/v2/processor/upgrade.go, build/buildkit/buildlayer/layerutils/manifests/manifests.go, build/buildkit/buildlayer/layerutils/utils.go, pkg/checker/check_list.go, pkg/config/config.go, pkg/env/env.go, pkg/filesystem/filesystem.go, pkg/plugin/etcd_backup_plugin.go, pkg/plugin/hostname_plugin.go, pkg/plugin/labels.go, pkg/runtime/kubeadm_config.go, pkg/runtime/kubeadm_runtime.go, pkg/runtime/registry.go, pkg/runtime/runtime.go, pkg/runtime/static_files.go, pkg/runtime/utils.go
- 1，function comments that do not start with the name of the exported element.
- 2，variable collides with import package name .
- 3,  delete unused comment.
=> fix static check issue

seautil/README.md
Help users quickly understand
Yes
seautil readme content translated into English
View this file
No
=> docs: seautil readme translate

LICENSE
=> hotfix LICENSE not read by github

apply/v2/run.go, common/structs.go, pkg/plugin/shell_plugin.go, sealer/cmd/run.go
=> Add the -e parameter and call wrapper

pkg/exec/exec.go, sealer/cmd/exec.go
#952 feature: add sealer exec command
=> #952 feature: add sealer exec command

docs/design/plugin_zh.md, docs/design/registry_zh.md, docs/site/src/docs/getting-started/plugin.md, filesystem/rootfs/docker/etc/daemon.json, pkg/runtime/init.go, sealer/cmd/delete.go
fix redundant adding hosts steps; 
remove insecure-registries from daemon.json
optimize plugin docs and add registry docs
=> fix redundant adding hosts steps and optimize docs

apply/v2/apply.go, apply/v2/applydriver/local.go, apply/v2/applydriver/utils.go, apply/v2/processor/install.go
=> feature:add app install process

docs/site/src/docs/help/faq.md
=> doc:add manually clean host env section on faq

pkg/env/env.go
=> Add && get environment variables

docs/site/src/docs/advanced/raw-docker-cloudimage.md
I find a wrong written in document about raw docker BaseImage
=> change a mistake about document

build/buildkit/buildimage/build_image.go, common/common.go, pkg/env/README.md, pkg/env/env.go, pkg/runtime/init.go, pkg/runtime/kubeadm.go, pkg/runtime/kubeadm_runtime.go, pkg/runtime/masters.go
=> refactor: simplify to make codes more readable

image/save/distributionpkg/proxy/proxyauth.go, image/save/distributionpkg/proxy/proxyregistry.go, image/save/save.go
This PR solve a problem about image save module. However, it is unsafe so the "golang-security-action" is failed.
what's unsafe is that it calls http.Get (in distribution/distribution source code) with a variable argument instead of a const argument.
=> fix a bug about image save

docs/design/global-config.md, docs/design/global-config_zh.md, sealer/cmd/run.go
=> modify how to use env docs

build/buildkit/buildimage/build_image.go
=> bugfix: set default metadata value if Metadata is nil

applications/loki-stack-fluentbit/Kubefile, applications/loki-stack-fluentbit/README.md, applications/loki-stack-fluentbit/fluentbit-loki-stack-system.yaml
This PR add loki-stack-fluentbit log support using longhorn storageclass.
#607 
#issuecomment-986387008
1. run a sealer longhorn:latest images cluster.
2. Install loki-stack-fluentbit in the cluster by using helm.
3. Get the loki-stack-fluentbit.yaml manifest file.
4. Add Kubefile
5. Run sealer build -f Kubefile -t loki-stack-fluentbit .
1. access the web dashboard
2. kubectl get pod,pvc,pv, check pod is running, pv & pvc has bound
NONE
=> feature: add loki-stack-fluentbit images support

.github/workflows/go.yml, utils/mount/overlay2.go, utils/mount/overlay2_test.go
1, refer to https://golangci-lint.run/usage/install/.  update the version, will avoid some false alarms
=> update golang ci lint to v1.43.0

applications/loki-stack-promtail/Kubefile, applications/loki-stack-promtail/README.md, applications/loki-stack-promtail/promtail-loki-stack.yaml
This PR add loki-stack-promtail log support using longhorn storageclass.
#607 
#issuecomment-986387008
1. run a sealer longhorn:latest images cluster.
2. Install loki-stack-promtail in the cluster by using helm.
3. Get the loki-stack-promtail.yaml manifest file.
4. Add Kubefile
5. Run sealer build -f Kubefile -t loki-stack-promtail .
1. access the web dashboard
2. kubectl get pod,pvc,pv, check pod is running, pv & pvc has bound
NONE
=> add loki-stack-promtail with longhorn support

pkg/filesystem/filesystem.go
=> init and clean plugin add wrapper

.github/workflows/go.yml
=> update go version

apply/v2/processor/delete.go
=> support adding custom cleanup scripts when deleting k8s cluster

apply/v2/run.go, docs/design/clusterfile-v2.md, pkg/env/env.go, pkg/plugin/plugins.go, plugin/plugins.go
fix apply error when env is empty,
fix plugin out of tree err 'plugin type not registered'
fix compat v1 cluster env
=> fix apply error when env is empty,

docs/design/clusterfile-v2.md, docs/design/global-config.md, docs/design/takeover-already-running-cluster.md, docs/site/src/docs/advanced/architecture.md, docs/site/src/docs/advanced/define-cloudrootfs.md, docs/site/src/docs/advanced/raw-docker-baseimage.md, docs/site/src/docs/advanced/use-kyverno-baseimage.md, docs/site/src/docs/getting-started/quick-start.md, docs/site/src/docs/help/contact.md, docs/site/src/docs/help/faq.md, docs/site/src/docs/reference/cloudrootfs.md, pkg/plugin/plugins.go, plugin/plugins.go
=> Fix doc typo

release_note.md
=> add v0.6.0 release note

pkg/filesystem/filesystem.go, pkg/runtime/init.go, pkg/runtime/masters.go, pkg/runtime/nodes.go
fix docker cert not send when sealer join command add node
clean docker cert
=> fix docker cert not send when sealer join command add node

.github/workflows/release.yml, docs/site/src/.vuepress/config.js
fix the release build failure
fix static page build err
=> fix the release build err

README.md, docs/README_zh.md, docs/site/src/docs/advanced/define-cloudrootfs.md, docs/site/src/docs/getting-started/quick-start.md, test/README.md
=> add release v0.6.0

applications/README.md, applications/skywalking/Kubefile, applications/skywalking/README.md, applications/skywalking/skywalking.yaml
This PR skywalking log support using longhorn storageclass.
#607 
#issuecomment-986387008
1. run a sealer longhorn:v1.2.3 images cluster.
2. Install skywalking in the cluster by using helm.
3. Get the skywalking.yaml manifest file.
4. Add Kubefile
5. Run sealer build -f Kubefile -t skywaling .
1. access the web dashboard
2. kubectl get pod,pvc,pv, check pod is running, pv & pvc has bound
NONE
=> feature: add sykwalking log application support && add images address

apply/v2/scale.go, pkg/runtime/kubeadm.go, pkg/runtime/kubeadm_config.go, utils/mount/overlay2.go
fix #1010 
fix annotation clusterfilename file not exist 
fix kubeadm config in Clusterfile is invalid
=> fix kubeadm config in Clusterfile is not work

image/save/save.go
=> add support for http

docs/site/src/docs/getting-started/build-appimage.md, sealer/cmd/build.go
=> doc:add build app image

docs/site/src/.vuepress/config.js, docs/site/src/docs/advanced/raw-docker-baseimage.md, docs/site/src/docs/advanced/use-kyverno-baseimage.md
=> Improve docs about raw docker baseimage

docs/design/image-save_zh.md
=> add docs about pull helm chart from registry, and save it

common/common.go, docs/design/global-config.md, docs/design/global-config_zh.md, docs/site/src/docs/advanced/develop-plugin.md, pkg/filesystem/filesystem.go
=> Render dir

apply/applydriver/local.go, docs/design/global-config.md, docs/design/global-config_zh.md, docs/site/src/docs/advanced/develop-plugin.md
=> bugfix: delete failed on master node

build/buildkit/buildimage/base_image.go, build/buildkit/buildimage/build_image.go, build/lite/lite_builder.go, build/local/local_builder.go, utils/mount/overlay2.go
=> bugfix: more precise on get rootfs info

apply/run.go, apply/scale.go
fix compatible clusterV1 invalid
=> fix compatible clusterV1 invalid

README.md, apply/applydriver/local.go, docs/README_zh.md, docs/site/src/docs/getting-started/quick-start.md, note.sh, pkg/filesystem/filesystem.go, release_note.md, test/README.md
=> add release v0.6.1

build/buildkit/buildinstruction/copy.go, build/buildkit/buildinstruction/utils.go, build/buildkit/buildlayer/utils.go
my build context : 
kubefile
test/
├── a.conf
├── b.conf
├── c.conf
└── yum
├── fssnap.d
├── vars
│   ├── contentdir
│   └── infra
└── version-groups.conf
COPY test/*.conf abc   : copy all file who has suffix ".conf" under test dir
COPY test/* abc : copy all files include hard links
COPY test/*.ccc abcd : failed to copy , thats because :  no such files ,so "test/*.ccc" not found
=> Build support wildcards copy

.github/workflows/release.yml
=> Fix the bug that the release cannot be uploaded to the OSS

image/save/interface.go, pkg/filesystem/filesystem.go, utils/ssh/scp.go
=> Fix sealer run display messages

apply/scale.go, pkg/infra/aliyun/ali_ecs.go, utils/strings.go, utils/strings_test.go
fix execute the join command repeatedly failed. #1065
=> fix execute the join command repeatedly failed.

pkg/image/merge.go, sealer/cmd/merge.go
1， bug fix related to issue #1019
2, download sealer images more efficiently
=> fix: merge image

pkg/filesystem/rootfs/docker/etc/daemon.json, pkg/filesystem/rootfs/docker/etc/docker.service, pkg/filesystem/rootfs/docker/scripts/clean-docker.sh, pkg/filesystem/rootfs/docker/scripts/clean.sh, pkg/filesystem/rootfs/docker/scripts/docker.sh, pkg/filesystem/rootfs/docker/scripts/init-registry.sh, pkg/filesystem/rootfs/docker/scripts/init.sh, pkg/filesystem/rootfs/rootfs/Kubefile, pkg/filesystem/rootfs/rootfs/etc/10-kubeadm.conf, pkg/filesystem/rootfs/rootfs/etc/Clusterfile, pkg/filesystem/rootfs/rootfs/etc/kubelet.service, pkg/filesystem/rootfs/rootfs/scripts/clean-kube.sh, pkg/filesystem/rootfs/rootfs/scripts/init-kube.sh, pkg/filesystem/rootfs/rootfs/scripts/kubelet-pre-start.sh, pkg/filesystem/rootfs/rootfs/statics/audit-policy.yml
=> move filesystem/rootfs to pkg

.github/workflows/go.yml, .github/workflows/gosec.yml
use official gosec action , update gosec to  v2.7.0.
reason:   gosec(securego/gosec:v2.2.0) doesn't support yet Go 1.16
=> update golang version

pkg/cert/cert.go, pkg/image/save/distributionpkg/proxy/proxyauth.go, pkg/image/save/distributionpkg/proxy/proxyregistry.go, pkg/image/save/save.go
=> sea.hub cretificate problems

pkg/filesystem/filesystem.go, pkg/runtime/init.go, pkg/runtime/kubeadm_runtime.go, pkg/runtime/masters.go, pkg/runtime/nodes.go, pkg/runtime/reset.go, utils/ssh/ssh.go
=> use the errgroup.Go function instead of goroutine

pkg/checker/check_list.go, pkg/checker/node_checker.go, sealer/cmd/check.go
fix run sealer check --pre failed #1047
=> fix run sealer check --pre failed

pkg/exec/exec.go, pkg/guest/guest.go, pkg/plugin/shell_plugin.go, pkg/runtime/kubeadm_runtime.go, sealer/cmd/exec.go, sealer/cmd/root.go, utils/ssh/ssh.go, utils/ssh/sshcmd.go, utils/ssh/sshcmd_test.go
=> fix:sealer exec not show cmd result

pkg/image/save/save.go
=> fix a small display bug

.github/workflows/gosec.yml, apply/applydriver/utils.go, build/cloud/utils.go, logger/file.go, pkg/checker/node_checker.go, pkg/checker/pod_checker.go, pkg/client/docker/images.go, pkg/client/k8s/client.go, pkg/debug/term.go, pkg/image/cache/chain.go, pkg/image/default_image_file.go, pkg/image/save/filesystem.go, pkg/image/store/distribution.go, pkg/image/store/layer_store.go, pkg/infra/aliyun/ali_ecs.go, pkg/plugin/etcd_backup_plugin.go, pkg/plugin/labels.go, pkg/plugin/plugins.go, pkg/plugin/test/label_nodes.go, utils/archive/compress.go, utils/file.go, utils/iputils.go, utils/mount/default.go, utils/mount/overlay2.go, utils/ssh/scp.go
=> use offical gosec action

pkg/filesystem/rootfs/docker/scripts/docker.sh, pkg/runtime/init.go, pkg/runtime/kubeadm.go, pkg/runtime/masters.go, pkg/runtime/nodes.go
fix CGroupDriver error not return
fix docker.sh failed to return error after execution:
=> fix CGroupDriver error not return

apply/processor/delete.go, pkg/plugin/labels.go
label phase should be PreGuest,Guest process might use label.
fix the PostClean plugin before the unmountRootfs step
=> modify label plugin phase PreGuest

pkg/image/distributionutil/push.go
=> display metadata infos on docker hub

pkg/image/save/save.go
=> fix a display bug

build/buildkit/buildimage/registry.go
```
FROM kubernetes:v1.19.8
COPY mychart charts 
COPY nginx charts/dev/gateway
COPY charts charts/test
COPY deploy/* charts/pro
```
=> chore: use deep traversal to search chart images

build/buildkit/buildimage/build_image.go, build/buildkit/buildimage/image_interface.go, build/buildkit/buildimage/utils.go, pkg/runtime/utils.go, types/api/v1/image_types.go
=> build: fill up image platform

apply/run.go, common/structs.go, docs/run_zh.md, sealer/cmd/run.go, utils/ssh/connect.go, utils/ssh/ssh.go, utils/ssh/sshcmd_test.go
run support custom port number.
=> run support custom port number.

pkg/filesystem/filesystem.go, utils/ssh/scp.go
=> fix a nil pointer bug

pkg/parser/parser.go, pkg/parser/parser_test.go
below is my test kubefile 
```
FROM kubernetes-arm64:v1.19.7
#FROM kubernetes:v1.19.8
RUN touch abc
COPY nginx charts
#COPY Clusterfile etc
#COPY Metadata .
RUN source /root/env.sh \
&& ls -l
RUN echo "Config ssh ..."\
&& echo "PermitRootLogin yes" >> /etc/ssh/sshd_config \
&& echo "Config ssh done ....."
RUN touch /tmp/abc
#COPY mychart charts
```
=> build kubefile support parser continuation character

build/buildkit/buildimage/build_image.go, pkg/image/distributionutil/push.go, sealer/cmd/tag.go
=> optimize save image process

.github/workflows/auto-build.yml
=> [WIP]Add auto-build action

go.mod, pkg/config/config.go, pkg/config/config_test.go, pkg/config/tigera-operator.yaml, types/api/v1/config_types.go, vendor/modules.txt
=> config support deep merge

apply/applydriver/local.go, apply/processor/create.go, pkg/runtime/runtime.go, sealer/cmd/apply.go, sealer/cmd/delete.go, test/suites/apply/apply.go, utils/utils.go
adding a request to the Apply step logic.
confirm actions when deleting and scaling down, do we need confirmation to add nodes?
=>  adding a request to the Apply step logic.

.github/workflows/auto-build.yml
=> optimization auto-build

docs/site/src/docs/getting-started/build-cloudimage.md
=> doc:add build arg

pkg/image/merge.go, sealer/cmd/merge.go, sealer/cmd/root.go
- fix:image merge lost cmd layer;
- fix:set new image name as required
=> fix:image merge lost cmd layer

docs/site/src/docs/getting-started/quick-start.md
fix quick-start.md kubernetes version use v1.19.8
=> fix quick-start.md kubernetes version use v1.19.8

pkg/filesystem/rootfs/docker/scripts/init-registry.sh
=> build support copy offline docker image to cloud image

docs/design/auto-build.md
Add Github Action auto-build docs
=> Add auto-build docs

docs/site/src/docs/getting-started/build-cloudimage.md, docs/site/src/docs/getting-started/plugin.md
=> doc: add user example of cmd-args

applications/README.md, applications/openebs/README.md, docs/site/src/docs/getting-started/applications.md, docs/site/src/zh/getting-started/applications.md
=> chore :fix doc deadlink

.github/workflows/oss-staticPages.yml, .github/workflows/release.yml
specify that the alibaba/sealer warehouse can be uploaded to the OSS.
=> specify that the alibaba/sealer warehouse can be uploaded to the OSS.

apply/run.go, utils/iputils.go
sealer run support ip range;
ip range from small to big order
=> sealer run support ip range;

docs/site/src/zh/getting-started/config.md
=> add zh config docs

pkg/image/default_image.go, pkg/image/image_interface.go, pkg/image/store/utils.go, pkg/prune/prune.go, sealer/cmd/prune.go
`sealer prune` command to clean up useless env
=> add the Prune interface to clean up useless environments

README.md, build/buildkit/buildimage/build_image.go, build/buildkit/buildimage/registry.go, build/lite/lite_builder.go, build/local/local_builder.go, docs/site/src/docs/getting-started/build-cloudimage.md, docs/site/src/docs/getting-started/quick-start.md, pkg/filesystem/cloudimage/cloudimage.go, sealer/cmd/build.go, utils/ssh/scp.go, utils/yaml.go
1. fix error log msg;
2. skip copy if src dir=dest dir;
3. set default build context as ".";
4. support cache docker images from ".tmpl" file.
=> chore: fix error log msg;skip copy if src dir=dest dir;

pkg/image/default_image_file.go, pkg/image/image_interface.go, sealer/cmd/save.go
support sealer save specify dir with default image name as tar filename.
`sealer save kubernetes:v1.19.8 -o /tmp`
=> support sealer save specify dir

docs/site/src/docs/advanced/arm-cloudimage.md
=> doc:add build section on arm cloud image

docs/site/src/docs/advanced/save-charts-package.md
=> doc:add save charts package

applications/nydus/nydusdfile/nydusd_scp_file/clean.sh, applications/nydus/nydusdfile/nydusd_scp_file/start.sh, applications/nydus/nydusdfile/serverclean.sh, applications/nydus/nydusdfile/serverstart.sh
force to delete nydusd service to clean the host environment.
=> bugfix: modify delete nydusd service logic

hack/autobuild.sh
=> Add autobuild script

docs/site/src/.vuepress/config.js, docs/site/src/zh/advanced/save-charts-package.md
fix failed to run static page action:
https://github.com/alibaba/sealer/runs/5401847838?check_suite_focus=true
=> fix failed to run static page action

.github/workflows/oss-staticPages.yml
=> make doc auto build on schedule

docs/site/src/docs/getting-started/build-cloudimage.md
=> doc:build support auth file

docs/design/plugin.md, docs/design/plugin_zh.md, docs/site/src/docs/getting-started/plugin.md, docs/site/src/zh/getting-started/plugin.md
optimize plugin docs, add taint plugin docs
=> add plugin docs

docs/site/src/docs/advanced/use-sealer-in-container.md, pkg/infra/container/imagecontext/build/Dockerfile
1. docker build -t base:v1 -f Dockerfile .
2. docker run --hostname master1 --name master1 --privileged --volume /lib/modules:/lib/modules:ro  --volume /var/lib/sealer:/var/lib/sealer --detach --tty base:v1
3.  in container master1 you can run sealer build
=> support run sealer build in container

apply/processor/install.go, pkg/plugin/plugins.go
=> feat:add plugin for app image run

pkg/gen/gen.go, sealer/cmd/gen.go
1. mark password and image name as required
2. add ssh port and ssh key
=> bugfix: mark password and image name as required for "sealer gen"

apply/run.go, common/structs.go, sealer/cmd/run.go, sealer/cmd/upgrade.go, utils/clusterfile_util.go
1. sealer run app image use existed cluster name
2. mark run port as uint16
=> sealer run app image use existed cluster name

build/buildkit/buildimage/build_image.go, build/buildkit/buildimage/image_interface.go, build/buildkit/buildimage/image_setter.go, build/buildkit/buildimage/metadata.go, build/buildkit/buildimage/middleware.go, build/buildkit/buildimage/shadow.go, common/common.go
1. set default clusterfile to image setter.
2. optimize the process of read metadata file.
=> optimize:process of build image setter

apply/applydriver/local.go, apply/applydriver/utils.go, build/buildkit/buildimage/build_image.go, common/common.go, pkg/guest/guest.go, pkg/image/merge.go, pkg/parser/parser.go, types/api/v1/image_types.go, types/api/v2/cluster_types.go, utils/env.go
=> Optimize set build cmd to image config

test/suites/apply/apply.go, utils/exec.go, utils/ssh/sshcmd.go
If the user is not root using sudo to exec local command.
If the ssh.user is not root using sudo to exec remote command.
=> support sudo to exec command and remote command. 

pkg/gen/gen.go, pkg/runtime/init.go, sealer/cmd/gen.go
fix `gen` cmd to take over the cluster
=> fix gen cmd to take over the cluster

docs/design/mutil_arch_build.md
=> Doc :design multi-arch build

README.md, docs/README_zh.md, docs/site/src/docs/advanced/arm-cloudimage.md, docs/site/src/docs/advanced/use-clusterfile.md, docs/site/src/docs/getting-started/quick-start.md, docs/site/src/zh/getting-started/quick-start.md, docs/site/src/zh/getting-started/using-clusterfile.md, pkg/env/env.go, pkg/env/env_test.go, release_note.md, test/README.md
=> add release v0.7.1

pkg/image/default_image.go
optimize the error log when the image does not exist
=> optimize the error log when the image does not exist

build/cloud_builder.go, pkg/env/env.go, pkg/filesystem/cloudfilesystem/overlay2.go, pkg/filesystem/rootfs/docker/scripts/clean.sh, pkg/filesystem/rootfs/docker/scripts/init-registry.sh, utils/ssh/connect.go, utils/ssh/scp.go, utils/ssh/scp_test.go, utils/ssh/ssh.go
optimize scripts:
check registry status is running;
rm -f /etc/docker/daemon.json
fix ssh.isFileExist function cause error:
=> optimize init registry scripts, fix ssh.isFileExist function cause error

apply/applydriver/local.go, apply/processor/create.go, apply/processor/delete.go, apply/processor/install.go, apply/processor/scale.go, docs/design/plugin.md, docs/design/plugin_zh.md, docs/site/src/docs/getting-started/plugin.md, docs/site/src/zh/getting-started/plugin.md, pkg/config/config.go, pkg/config/config_test.go, pkg/plugin/hostname_plugin.go, pkg/plugin/labels.go, pkg/plugin/plugin.go, pkg/plugin/plugins.go, pkg/plugin/plugins_test.go, pkg/plugin/shell_plugin.go, pkg/plugin/taint_plugin.go, types/api/v2/cluster_types.go
The plugins are also deployed when 'Sealer join' is executed
=> The plugins are also deployed when 'Sealer join' is executed

apply/applydriver/local.go, apply/processor/create.go, common/common.go, pkg/config/config.go, pkg/filesystem/cloudfilesystem/nydus.go, pkg/filesystem/cloudfilesystem/overlay2.go, pkg/filesystem/cloudimage/cloudimage.go, pkg/filesystem/filesystem.go, pkg/gen/gen.go, pkg/runtime/kubeadm_runtime.go, utils/platform/cpu.go, utils/platform/platform.go, utils/ssh/platform.go, utils/ssh/ssh.go
=> support multi arch run

apply/applydriver/interface.go, apply/applydriver/local.go, apply/processor/upgrade.go, sealer/cmd/upgrade.go
separate the upgrade module from apply module.
=> separate the upgrade module from apply module.

pkg/image/distributionutil/login.go, pkg/image/save/distributionpkg/proxy/proxyregistry.go
use /etc/docker/certs.d/ directory certificate:
fix build pulls the private repository image;
fix login private repo;
=> fix build pulls the private repository image

build/buildkit/buildimage/differ.go, build/buildkit/buildimage/executor.go, build/buildkit/buildimage/image_interface.go, build/buildkit/buildimage/middleware.go, build/buildkit/buildinstruction/copy.go, pkg/image/store/filesystem.go, sealer/cmd/images.go
order image list as created time
=> arrange image list in order

pkg/image/merge.go, pkg/image/store/filesystem.go, sealer/cmd/merge.go
=> bugfix: image merge support specify platform

docs/design/plugin.md, docs/design/plugin_zh.md, docs/site/src/docs/getting-started/plugin.md, docs/site/src/zh/getting-started/plugin.md, pkg/env/env.go, pkg/infra/Clusterfile, pkg/plugin/plugin.go
=> modify env WrapperShell  && Change capital TAINT

docs/design/build_zh.md, docs/design/mutil_arch_build.md, docs/site/src/docs/getting-started/build-cloudimage.md, docs/site/src/zh/getting-started/build-cloudimage.md, sealer/cmd/cert.go, sealer/cmd/debug.go, sealer/cmd/delete.go, sealer/cmd/join.go, sealer/cmd/load.go, sealer/cmd/login.go, sealer/cmd/prune.go, sealer/cmd/run.go, sealer/cmd/save.go, sealer/cmd/tag.go, sealer/cmd/upgrade.go, sealer/cmd/version.go
=> Doc: fix cmd typo; add mutil arch examples for build

apply/apply.go, apply/applydriver/local.go, apply/processor/create.go, apply/processor/delete.go, apply/processor/gen.go, apply/processor/install.go, apply/processor/interface.go, apply/processor/scale.go, pkg/clusterfile/clusterfile.go, pkg/plugin/plugins_test.go, sealer/cmd/cert.go, sealer/cmd/gen.go
optimize the processor execute interface
because create Processor, Delete Processor, Install Processor, and Scale Processor all contain pipelines, extract the exec pipeline function.
```shell
func (e *Executor) Execute(cluster *v2.Cluster) error {
pipLine, err := e.GetPipeLine()
if err != nil {
return err
}
for _, f := range pipLine {
if err = f(cluster); err != nil {
return err
}
}
return nil
}
```
=> optimize the processor execute interface

pkg/image/distributionutil/blob.go, pkg/image/save/distributionpkg/proxy/proxyblobstore.go, pkg/image/save/save.go
=> fix build cause OOM when saving images from imageList file

README.md, docs/README_zh.md, docs/site/src/docs/getting-started/quick-start.md, docs/site/src/zh/getting-started/quick-start.md, release_note.md, test/README.md
=> add release v0.8.0

.github/workflows/auto-build.yml, docs/site/src/docs/reference/clusterfile.md
Update auto build image workflow actions
=> Update auto build image workflow actions

pkg/image/default_image.go, pkg/image/image_interface.go, pkg/image/store/utils.go, pkg/prune/build_pruner.go, pkg/prune/image_pruner.go, pkg/prune/layer_pruner.go, pkg/prune/prune.go, sealer/cmd/prune.go, utils/file.go
=> Feat: add image db pruner and build tmp pruner

build/buildimage/middleware.go, pkg/image/save/interface.go, pkg/image/save/save.go, pkg/image/save/save_test.go, pkg/image/save/utils.go
=> bugfix: support pull imageListWithAuth.yaml from same repo and same auth

apply/applydriver/local.go, apply/processor/create.go, apply/processor/gen.go, apply/processor/scale.go, pkg/runtime/init.go, pkg/runtime/kubeadm_config.go, pkg/runtime/kubeadm_runtime.go, pkg/runtime/masters.go, pkg/runtime/nodes.go, pkg/runtime/registry.go, pkg/runtime/reset.go, pkg/runtime/runtime.go
SeaHub CertSans is added by default
=> SeaHub CertSans is added by default

pkg/cert/cert.go, pkg/cert/cert_cmd.go, pkg/runtime/init.go, pkg/runtime/kubeadm_config.go, pkg/runtime/kubeadm_types/v1beta2/types.go, pkg/runtime/masters.go, pkg/runtime/nodes.go, pkg/runtime/registry.go, pkg/runtime/reset.go
add `sea.hub` dns name of registry cert by default
=> add `sea.hub` dns name of registry cert by default

pkg/image/default_image.go, pkg/image/image_interface.go, pkg/image/store/filesystem.go, sealer/cmd/rmi.go, utils/mount/overlay2.go
1. add delete image by id
2. use lazy mount for apply mount cloud image
=> bugfix: add delete image by id

applications/nydus/nydusdfile/clientfile/clean.sh, applications/nydus/nydusdfile/clientfile/start.sh
=> optimize nydus shell script

apply/applydriver/local.go, apply/processor/create.go, apply/processor/gen.go, apply/processor/install.go, apply/processor/scale.go, apply/processor/upgrade.go, apply/run.go, pkg/filesystem/cloudimage/cloudimage.go, pkg/guest/guest.go
=> bugfix:fix run config and run plugin nil point panic

pkg/image/util.go, sealer/cmd/inspect.go
=> bugfix:support inspect image by name

applications/nydus/nydusdfile/clientfile/start.sh, docs/site/src/zh/getting-started/plugin.md, docs/site/src/zh/getting-started/using-clusterfile.md, pkg/env/env.go, pkg/filesystem/cloudfilesystem/nydus.go, pkg/filesystem/cloudfilesystem/overlay2.go, pkg/filesystem/cloudfilesystem/utils.go
bugfix failed to umount rootfs
=> bugfix failed to umount rootfs

README.md, docs/README_zh.md, docs/site/src/docs/advanced/arm-cloudimage.md, docs/site/src/docs/getting-started/quick-start.md, docs/site/src/zh/getting-started/quick-start.md, release_note.md, test/README.md
=> add release v0.8.3

pkg/image/distributionutil/repository.go, pkg/image/reference/reference.go, sealer/cmd/search.go
add the search command to search for image tags
=> add the search command to search for image tags

README.md, docs/README_zh.md, docs/site/src/docs/advanced/arm-cloudimage.md, docs/site/src/docs/getting-started/plugin.md, docs/site/src/docs/getting-started/quick-start.md, docs/site/src/zh/getting-started/quick-start.md, note.sh, pkg/plugin/plugins.go, release_note.md, test/README.md
=> add release v0.8.4

build/buildimage/saver.go, build/buildimage/setter.go, build/buildimage/utils.go
=> bugfix: no need to get clusterfile content form all layers

README.md, docs/README_zh.md, docs/site/src/docs/advanced/arm-cloudimage.md, docs/site/src/docs/getting-started/quick-start.md, docs/site/src/zh/getting-started/quick-start.md, release_note.md, test/README.md
=> doc:add release v0.8.5

README.md
docs: add twitter badge for sealer project
none
none
none
none
=> docs: add twitter badge for sealer project

README.md, apply/applydriver/local.go, apply/processor/scale.go, docs/site/src/.vuepress/config.js, docs/site/src/docs/advanced/define-cloudimage.md, docs/site/src/zh/reference/clusterfile.md, docs/test-report/release-v0.1.5.md, hack/autobuild.sh, utils/iputils.go, utils/utils.go
VSCode automatically scanned out several Chinese comma, just correct them.
In addition, this PR corrects the README.md on a consecutive blank line which is introduced in https://github.com/sealerio/sealer/pull/1354
none
none
none
none
=> fix Chinese comma to be English

pkg/runtime/kubeadm_config.go
=> remove duplicate ip cert sans

sealer/cmd/root.go, version/version.go
1. cmd: add root command description
2. output sealer version when failure to reduce the support time
none
none
none
none
=> cmd: add root command description and output sealer version when failure

apply/processor/delete.go, pkg/filesystem/cloudfilesystem/nydus.go, pkg/filesystem/cloudfilesystem/overlay2.go, pkg/filesystem/filesystem_test.go, pkg/guest/guest.go, pkg/runtime/utils.go, types/api/v2/cluster_types.go
fixed obtaining the master0 ip address function.
=> fix: wrong function to get master IP address

docs/site/src/.vuepress/config.js, docs/site/src/index.md, docs/site/src/zh/index.md
=> modify logo

pkg/filesystem/rootfs/docker/etc/daemon.json
Signed-off-by: kakzhou719 <wb-zl958011@alibaba-inc.com>
=> change docker cgroupdriver to systemd

apply/run.go, apply/run_test.go, apply/scale.go, cmd/seautil/cmd/route.go, pkg/filesystem/cloudfilesystem/nydus.go, pkg/plugin/taint_plugin.go, pkg/plugin/utils.go, pkg/runtime/kubeadm_runtime.go, pkg/runtime/masters.go, pkg/runtime/nodes.go, pkg/runtime/registry.go, test/testhelper/utils.go, utils/net/cidr.go, utils/net/iputils.go, utils/net/route.go, utils/ssh/platform.go, utils/ssh/scp.go, utils/ssh/ssh.go, utils/ssh/sshcmd.go
=> chore: separate net pkg from utils

logger/conn.go, logger/console.go, logger/file.go, logger/log.go
=> Revise Chinese notes to English

README.md
Add communication channels in sealer's README.md.
includes:
* CNCF mailing list: to be added;
* twitter
* dingtalk group number and scan code picture.
none
none
none
none
=> docs: add sealer communication channels in README.md

docs/design/Kubefile.md
I think the core concept of sealer is `Kubefile`. 
This pull request illustrates Kubefile in much more aspects. And it could make readers to understand Kubefile much better.
Beside this, we should also add details document for `CloudImage` and `Clusterfile` which would be follow-ups.
none
none
none
none
=> docs: add a detailed introduction of Kubefile

pkg/filesystem/rootfs/docker/scripts/docker.sh, pkg/filesystem/rootfs/docker/scripts/init-registry.sh
=> bugfix:load offline images into CloudImage

docs/design/clusterfile-v2.md, pkg/runtime/default_kubeadm_config.go
Signed-off-by: wb-hjh933779 <wb-hjh933779@alibaba-inc.com>
remove the library path of the imageRepository configured by kubeadm.
=> remove the library path of the imageRepository configured by kubeadm

go.mod, pkg/cert/kube_certs.go, vendor/k8s.io/utils/net/ipnet.go, vendor/k8s.io/utils/net/net.go, vendor/k8s.io/utils/net/port.go, vendor/modules.txt
https://github.com/sealerio/sealer/issues/1419
=> fix: generate wrong apiserver certificate when modify svcCidr 

pkg/clusterfile/util.go, pkg/image/distributionutil/push.go, pkg/image/distributionutil/utils.go
=> bugfix: set right size of manifest descriptor for sealer push

pkg/runtime/init.go, pkg/runtime/masters.go, utils/ssh/connect.go
Signed-off-by: xiaoning.tan <tanxiaoning007@qq.com>
Fixes: #1431
=> bugfix: k8s admin configuration file is not copied to current user

Adopters.md
update adopters to add more details
add adopter status and best practice if there is.
=> docs: update adopters to add more details

logger/file.go, logger/log.go, pkg/image/distributionutil/utils.go, utils/exec/exec.go, utils/ssh/sshcmd.go, utils/ssh/utils.go
=> Bugfix: set debug level as default for file logger

apply/apply.go, common/common.go, pkg/plugin/taint_plugin.go, pkg/runtime/registry.go, test/suites/apply/apply.go, test/suites/apply/fixtures/config_plugin_for_test.yaml
fix taint not working: #1435 
Signed-off-by: wb-hjh933779 <wb-hjh933779@alibaba-inc.com>
=> fix taint not working

apply/processor/gen.go, utils/yaml/yaml.go
=> fix Clusterfile not create bug

.github/weekly-digest.yml 
This pull request add the github app [weekly-digest](https://github.com/abhijeetps/weekly-digest). The effect would be like the following:
none
none
none
none
=> setup: add weekly digest for sealer

.github/labeler.yml, .github/workflows/labeler.yml
Add github action labeler for sealer. All details are listed here: https://github.com/marketplace/actions/labeler
For which labels would be added:
* already listed in the .github/labeler.yml
* if we need to add more labels, we could update file above later.
none
none
none
none
=> chore: add github labeler action for sealer

.github/workflows/unit-test.yml, build/layerutils/charts/charts_test.go, build/layerutils/charts/helm_test.go, build/layerutils/manifests/manifests_test.go, pkg/config/config_test.go, pkg/config/pre_process_test.go, pkg/debug/clusterinfo/clusterinfo_test.go, pkg/env/env_test.go, pkg/filesystem/filesystem_test.go, pkg/image/save/save_test.go, pkg/image/store/image_store_test.go, pkg/infra/infra_test.go, pkg/infra/test/infra_test.go, pkg/ipvs/ipvs_test.go, pkg/plugin/etcd_backup_plugin_test.go, pkg/plugin/plugins_test.go, utils/archive/compress_test.go, utils/decode_test.go, utils/mount/default_test.go, utils/mount/overlay2_test.go, utils/os/fs/filesystem_test.go, utils/os/readers_test.go, utils/ssh/scp_test.go, utils/ssh/sshcmd_test.go
After executing the unit test case of sealer, we found there are quite a lot of failure case which may lead to the poor quality of itself.  This has already be described in https://github.com/sealerio/sealer/issues/1360 . 
This pull request did:
* make the go test `go list ./... | grep -v /test` work. here we exclude the test dir, since the test dir is used to e2e-test in integration test scenario;
* add codecov action for sealer including `go test `. With this, we could  have unit test for each future pull request, and will post a codecov comment on each pull request.
* commented quite a lot of failure unit test case. To make the unit test work, I comment all the failure case. Because I care more about the normal functionality of …
=> test: make unit test work and add codecov github action

MAINTAINERS.md
update maintainers info to add emails
=> docs: update maintainers info to add emails

README.md, code-of-conduct.md
In https://github.com/cncf/toc/issues/831, CNCF suggests that:
GitHub: ensure that hat the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
So, update that to meet CNCF's demand.
=> docs: add CNCF code of conduct in readme to meet CNCF's request

pkg/client/k8s/client.go, pkg/runtime/update_cert.go
fix sealer cert --alt-names bug
fix https://github.com/sealerio/sealer/issues/1539
using sealer cert -- alt-names ip, you can view kubeadm.yaml file,
view whether cert in the  file retains the original service IP and adds a new one
=> fix sealer cert --alt-names bug

utils/platform/cpu.go
Signed-off-by: sfeng1996 <SFeng1996@163.com>
Fixes #1559
=> fix: panic when pull arm image

.github/workflows/e2e-test-apply.yml, .github/workflows/go.yml, .github/workflows/unit-test.yml
In https://github.com/sealerio/sealer/pull/1563 , I found that we have no way to check if a unit test case runs in CI. So I add `-v` flag into unit-test action.
In addition, I unified all the golang verison in all actions' environment.
none
none
=> action: update go version and add -v flag to go test

.github/release-drafter.yml, README.md, cmd/sealer/cmd/root.go, docs/README_zh.md, pkg/infra/aliyun/ali_provider.go, release_note.md, test/README.md
1. add `refactor` release drafter 
2. delete unused release note
3. panic when failed to init logger
4. write clusterfile without encrypt password for e2e test
5.  modify doc of sealer version v0.8.6
=> add release v0.8.6

.github/workflows/release.yml
=> add release permission

pkg/parser/parser.go
When parsing Kubefile, we should fail fast when parsing invalid content.  
Code updated in this pull request, just throw an log and make the program move on. I think that is quiet unfriendly for end users. Just improve that.
none
none
none
none
=> fix: make fail fast when parsing invalid content in Kubefile

README.md
add codecov badge for sealer. And we see the unit test coverage of sealer is only 11%. 
sealer community needs more efforts on test coverage. 
none
none
none
none
=> add codecov badge for sealer

apply/processor/create.go, apply/processor/delete.go, apply/processor/gen.go, apply/processor/install.go, apply/processor/scale.go, apply/processor/upgrade.go, build/buildimage/saver.go, cmd/sealer/cmd/alpha/exec.go, pkg/config/config_test.go, pkg/debug/clusterinfo/clusterinfo_test.go, pkg/env/env_test.go, pkg/exec/exec_test.go, pkg/filesystem/clusterimage/clusterimage.go, pkg/infra/aliyun/ali_ecs.go, pkg/plugin/shell_plugin.go, utils/mount/mount_service.go, utils/mount/overlay2_test.go, utils/ssh/utils.go
modify unit test 
modify the method of obtaining master ip and node ip
=> modify the method to get the node ip

README.md
1. a concise examples of the quick start
2. make introduction more brief
3. aggregation and consolidation of features
=> doc: make Readme more readable

CONTRIBUTING.md
To make CONTRIBUTING meet the requirments of DCO
add --signoff in git commit
=> docs: add git --signoff

.github/workflows/auto-build.yml, .github/workflows/e2e-test-apply.yml, .github/workflows/e2e-test-build.yml, .github/workflows/e2e-test-image.yml, .github/workflows/e2e-test-run.yml, .github/workflows/go.yml, .github/workflows/unit-test.yml
Add deps installation for sealer build.
(buildah containers need this.)
=> upgrade action

.github/workflows/e2e-test-apply.yml, .github/workflows/e2e-test-build.yml, .github/workflows/e2e-test-image.yml, .github/workflows/e2e-test-run.yml
Signed-off-by: David Bao <baojn1998@163.com>
go get will affect go vendor.
=> change get to install

docs/design/kubefile_alpha.md
related to [[Proposal] A more k8s-based/rootfs-transparent instructions in Kubefile](https://github.com/sealerio/sealer/issues/1579)
For CNI/CSI/APP, I still fail to think throgh the dynamic render for remote fetching(https) files at runtime (this is easy to accomplish at local). 
This is note a ultimate version, propose this to have a discussion with you guys. @sealerio/sealer-maintainers @sealerio/sealer-reviewers
=> [proposal] propose new instructions in kubefile

cmd/sealer/cmd/run.go, pkg/infradriver/infradriver.go, pkg/infradriver/ssh_infradriver.go, pkg/runtime/interface.go
Through the re-encapsulation of the ssh package, the cluster operation can be completed directly through the ip address, instead of passing the v2.cluster structure to the ssh inner layer as before we do.
=> add ssh infra driver

pkg/container-runtime/containerdInstaller.go, pkg/container-runtime/dockerInstaller.go, pkg/container-runtime/installer.go
Install docker:
Modify the docker configuration file through shell commands
Execute the clean script file when uninstalling
=> Add Container runtime---docker install

pkg/clustercert/kubeconfig.go, pkg/logger/formatter.go
Fix:  different log colors。
Fixes #1584
=> bugfix: fix different log colors

cmd/sealer/cmd/build.go, docs/design/build_zh.md, pkg/define/options/options.go, test/sealer_build_test.go, test/suites/build/build.go
Currently sealer only supports one build type, then no need to add a build command flag of build type.
none
none
none
none
=> remove build type flag for build command

cmd/sealer/cmd/delete.go, cmd/sealer/cmd/join.go, cmd/sealer/cmd/run.go, pkg/cluster-runtime/hook.go, pkg/cluster-runtime/installer.go, pkg/registry/singleton.go
1. Add installer hooks 
2. hook execution order is alphabetical by name.
3. hooks that are not registered in sealer will return an error, at present ,only add shell hook at installer hook list.
4.  if "on" field at hookConfig is not set, then use all host ip as default.
5.  Transfer plugin "action" to hook "phase".
6. complete installation process to set RuntimeConfig.
=> Add installer hooks 

pkg/runtime/interface.go, pkg/runtime/kubernetes/driver.go, pkg/runtime/kubernetes/init.go, pkg/runtime/kubernetes/join_masters.go, pkg/runtime/kubernetes/join_nodes.go, pkg/runtime/kubernetes/runtime.go, pkg/runtime/kubernetes/utils.go
1. add k8s runtime driver
2. add init Kubelet Service in installation and scale up process.
3. add reconcile cluster status after cluster init: currently only save admin config file to cluster as secret resource.
=> Supplement the installation processes in k8s runtime

utils/mount/overlay2.go
relaxing overlay mount restrictions
Fixes #1547
=> feat: relaxing overlay mount restrictions

pkg/clusterfile/clusterfile.go, pkg/clusterfile/clusterfile_test.go, pkg/clusterfile/decoder_test.go, pkg/clusterfile/test/testclusterfile.yaml
Fix the bug that the saveall function cannot omit null bytes
=> Fix saveAll funcation and add unit test

cmd/sealer/cmd/image/rmi.go, pkg/define/options/options.go, pkg/imageengine/buildah/rmi.go
Remove flag `--all` for rmi. #1711
=> remove --all flag for rmi

cmd/sealer/cmd/utils/hosts.go, pkg/cluster-runtime/hook.go, pkg/cluster-runtime/installer.go, pkg/clusterfile/clusterfile_test.go, pkg/clusterfile/decoder_test.go, pkg/imagedistributor/scp_distributor.go, pkg/infradriver/infradriver.go, pkg/infradriver/ssh_infradriver.go, pkg/registry/singleton.go, pkg/runtime/kubernetes/init.go, pkg/runtime/kubernetes/kubeadm_config/kubeadm_config.go, utils/ssh/scp.go
=> [WIP]bugfix for sealer run

pkg/clusterfile/clusterfile.go
Fix: ensure clusterfile path not empty
#1720
=> Fix: ensure clusterfile path not empty

.github/workflows/auto-build.yml, .github/workflows/e2e-test-apply.yml, .github/workflows/e2e-test-build.yml, .github/workflows/e2e-test-image.yml, .github/workflows/e2e-test-run.yml, .github/workflows/go.yml, .github/workflows/release.yml, .github/workflows/unit-test.yml
=> add apt-get update in workflows

cmd/sealer/cmd/image/pull.go
Signed-off-by: HIHIA <283304489@qq.com>
set default image pull policy as always, and add ifnewer in usage
Fixes #1453
=> feat: set default image pull policy as always

cmd/sealer/cmd/utils/cluster.go, cmd/sealer/cmd/utils/hosts.go
fix the format for saving the cluster IP address
eg:
=> Fix： the format for saving the cluster IP address

cmd/sealer/cmd/image/image.go
There is duplicate cmd load now, we just need one.
NONE
=> delete duplicate cmd load

cmd/sealer/cmd/cluster/join.go, cmd/sealer/cmd/cluster/run.go, pkg/runtime/kubernetes/clean.go, pkg/runtime/kubernetes/runtime.go
1. support to clean cluster if failed to run cluster image
2. cluster reset do not need to delete nodes if we delete all cluster.
=> bugfix: support to clean cluster if failed to run cluster image

pkg/cluster-runtime/installer.go, pkg/cluster-runtime/scale.go, pkg/cluster-runtime/uninstall.go, pkg/infradriver/infradriver.go, pkg/infradriver/ssh_infradriver.go, pkg/registry/singleton.go, pkg/runtime/kubernetes/init.go, pkg/runtime/kubernetes/join_masters.go, pkg/runtime/kubernetes/join_nodes.go, types/api/v2/cluster_types.go, utils/shellcommand/hostsfile.go
1. add cluster level host aliases 
2. support to set host aliases at run and scale up
3. support to delete host aliases at delete and scale down
=> support to set host aliases via clusterfile

pkg/cluster-runtime/installer.go
1. add custom domain
2. add custom registry username
3. add custom registry password
=> support to get registry config from cluster env

pkg/container-runtime/installer.go, pkg/registry/driver.go, pkg/registry/singleton.go, pkg/runtime/kubernetes/runtime.go
1. configure registry access credential via sdk, gen config.json locally and send to all hosts which needed to access registry.
=> optimize: configure registry access credential via sdk

pkg/cluster-runtime/hook.go
1.  bugfix:run shell plugins on rootfs
=> bugfix: run shell plugins on rootfs

cmd/sealer/cmd/cluster/join.go, cmd/sealer/cmd/utils/cluster.go, cmd/sealer/cmd/utils/cluster_test.go
bugfix: add independent host at cluster for sealer join
if joined host have different ssh auth info, only add joined ip string to cluster which is not not meet expectation.
=> bugfix: add independent host at cluster for sealer join

pkg/cluster-runtime/installer.go, pkg/cluster-runtime/scale.go, pkg/registry/configurator.go, pkg/registry/external.go, pkg/registry/singleton.go
1. no need launch local registry when join node
2. `InstallOn` will install registry configuration on each given hosts, such as auth info and certs. 
3. `Launch` only start built-in cluster registry component.
=> optimize:no need launch local registry when join node

pkg/cluster-runtime/installer.go
…ory under rootfs
1. Distribute rootfs and ensure that there is an application directory under rootfs
=> fix: Distribute rootfs

cmd/sealer/cmd/cluster/cluster.go, cmd/sealer/cmd/cluster/scale-up.go
Add nodes to clusters by extending node IP addresses
=> Add scale-up command

cmd/sealer/cmd/cluster/apply.go, cmd/sealer/cmd/cluster/cluster.go, cmd/sealer/cmd/cluster/delete.go
support apply command
apply == run
=> support apply command

cmd/sealer/cmd/cluster/delete.go, pkg/imagedistributor/scp_distributor.go
Signed-off-by: HIHIA <283304489@qq.com>
delete cluster add prune options
Fixes #1786
=> delete cluster add prune options

cmd/sealer/cmd/cluster/apply.go
1. add log message for apply, include creating cluster, scaling up cluster, installing applications ,
2. delete redundant cobra flag: `Clusterfile`.
=> add log message for sealer apply

pkg/runtime/kubernetes/runtime.go
=> Remove unprofessional descriptions.

utils/ssh/connect.go
=> Fix concurrent map read bug.

cmd/sealer/cmd/alpha/debug.go, cmd/sealer/cmd/alpha/exec.go, cmd/sealer/cmd/alpha/gen.go, cmd/sealer/cmd/alpha/merge.go, cmd/sealer/cmd/alpha/upgrade.go, cmd/sealer/cmd/cluster/apply.go, cmd/sealer/cmd/cluster/cert.go, cmd/sealer/cmd/cluster/check.go, cmd/sealer/cmd/cluster/delete.go, cmd/sealer/cmd/cluster/join.go, cmd/sealer/cmd/cluster/run-app.go, cmd/sealer/cmd/cluster/run.go, cmd/sealer/cmd/cluster/scale-up.go, cmd/sealer/cmd/completion.go, cmd/sealer/cmd/image/build.go, cmd/sealer/cmd/image/images.go, cmd/sealer/cmd/image/inspect.go, cmd/sealer/cmd/image/load.go, cmd/sealer/cmd/image/login.go, cmd/sealer/cmd/image/logout.go, cmd/sealer/cmd/image/pull.go, cmd/sealer/cmd/image/push.go, cmd/sealer/cmd/image/rmi.go, cmd/sealer/cmd/image/save.go, cmd/sealer/cmd/image/search.go, cmd/sealer/cmd/image/tag.go, cmd/sealer/cmd/root.go, cmd/sealer/cmd/version.go, cmd/sealer/main.go
polish cmd discription to add user readablity
=> cmd: polish cmd discription to add user readablity

cmd/sealer/cmd/alpha/alpha.go, cmd/sealer/cmd/alpha/check.go, cmd/sealer/cmd/cluster/cluster.go
=> move check to alpha module

pkg/imageengine/buildah/manifest.go, pkg/imageengine/buildah/push.go
chore: delete fmt debug message
=> chore: delete fmt debug message

cmd/sealer/cmd/cluster/run-app.go
In special scenarios, we want to load app images to the specified registry in advance.
support only loadImage apply mode
=> support only load app image apply mode

pkg/cluster-runtime/hook.go, pkg/logger/formatter.go, pkg/logger/logger_test.go
=> bugfix: use right time stamp format

cmd/sealer/cmd/alpha/alpha.go, cmd/sealer/cmd/alpha/manifest.go, cmd/sealer/cmd/image/image.go
=> move manifest to alpha

cmd/sealer/cmd/cluster/apply.go, cmd/sealer/cmd/utils/cluster.go, common/common.go, pkg/cluster-runtime/scale.go, pkg/cluster-runtime/uninstall.go, pkg/clusterfile/clusterfile.go, pkg/ipvs/ipvs.go, pkg/ipvs/ipvs_test.go, pkg/registry/local.go, pkg/runtime/kubernetes/clean.go, pkg/runtime/kubernetes/join_nodes.go, pkg/runtime/kubernetes/runtime.go, pkg/runtime/kubernetes/utils.go
=> Fix: set ipvscare static pod for local HA registry.

build/kubefile/parser/utils.go, pkg/registry/external.go, pkg/registry/local.go
1. rename some variables
2. use `net.JoinHostPort` to join host port
=> chore: rename variables

.github/workflows/release.yml
=> update release.yaml run os to ubuntu-latest

.github/workflows/release.yml
=> no need save sealer binary to oss

.github/workflows/go.yml, .github/workflows/release.yml, README.md
=> use ubuntu-20.04 as run-on os to build sealer binary 

.github/workflows/go.yml, .github/workflows/gosec.yml, .github/workflows/markdown.yml, .github/workflows/release.yml, .github/workflows/unit-test.yml
1. no need todo markdown check for doc command line thats because it no longer exist.
2. add  ignore paths for build, gosec, uttest, release
=> Optimize github ci action

cmd/sealer/cmd/cluster/run.go
sealer run app failed
Fixes: #1948
=> fix run app bug

cmd/sealer/cmd/cluster/apply.go, cmd/sealer/cmd/cluster/delete.go, cmd/sealer/cmd/cluster/join.go, cmd/sealer/cmd/cluster/run.go, cmd/sealer/cmd/cluster/scale-up.go, cmd/sealer/cmd/types/types.go, cmd/sealer/cmd/utils/cluster.go, cmd/sealer/cmd/utils/cluster_test.go, cmd/sealer/cmd/utils/hosts.go, cmd/sealer/cmd/utils/hosts_test.go, cmd/sealer/cmd/utils/validate.go
1. support merge flags when use clusterfile for run and apply
2. bugfix: no need to specify master ip when run app image
3. optimize: each cmd use their own flags
=> support merge flags when use clusterfile for run and apply

docs/design/global-config.md, docs/design/global-config_zh.md, pkg/plugin/plugins.go, pkg/plugin/utils.go
When running the plugin script, the values in the plugins do not take effect.
I have found the cause of the problem: there is a problem with the repeated judgment function in plugins, which causes the plugin to not execute.
so i fix it.
=> fix plugin bug

cmd/sealer/cmd/cluster/apply.go
=> bugfix: use applyMode for apply cli

cmd/sealer/cmd/utils/cluster.go, common/common.go, docs/api/clusterfile.md, docs/design/global-config.md, docs/design/plugin.md, pkg/cluster-runtime/hook_test.go, pkg/cluster-runtime/test/test.yaml, pkg/clusterfile/clusterfile.go, pkg/clusterfile/clusterfile_test.go, pkg/clusterfile/decoder.go, pkg/clusterfile/decoder_test.go, pkg/config/pre_process.go, pkg/imagedistributor/scp_distributor.go, test/suites/apply/apply.go, test/suites/apply/fixtures/config_plugin_for_test.yaml, types/api/constants/constants.go, types/api/v1/config_types.go, types/api/v1/groupversion_info.go, types/api/v2/groupversion_info.go, utils/decode.go, utils/test/file/Clusterfile
=> use const as resource kind

common/common.go, pkg/registry/local.go, pkg/runtime/kubernetes/runtime.go
we can overwrite the default ipvs VIP through  cluster env.
=> feat: support ipvs vip overwriting 

build/buildimage/differ.go, build/buildimage/middleware.go, build/kubefile/parser/image_engine_test.go, build/layerutils/utils.go, build/layerutils/utils_test.go, cmd/sealer/cmd/image/build.go, pkg/define/image/v1/sealer_image_extension.go, pkg/define/options/options.go, pkg/imageengine/buildah/config.go, pkg/imageengine/buildah/inspect.go, pkg/imageengine/interface.go
Fixes https://github.com/sealerio/sealer/pull/1960
=> feature: store container image list to image spec

pkg/define/application/v1/application.go, pkg/registry/local.go, pkg/runtime/kubernetes/runtime.go
=> bugfix: use ipv6  env and app cmd

pkg/runtime/kubernetes/join_masters.go
=> Fix scheduler and kcm connect master0 bug.

README.md, cmd/sealer/cmd/cluster/delete.go, cmd/sealer/cmd/cluster/run.go, cmd/sealer/cmd/image/build.go
1. Update readme
2. modify image name
=> modify the command line examples

pkg/registry/local.go, pkg/runtime/kubernetes/utils.go
=> Modify filepath->path

build/kubefile/parser/app_handler.go, build/kubefile/parser/utils.go
=> Bugfix for app parser

cmd/sealer/cmd/alpha/mount.go
If the image is too small, the container directory will be mounted without being created, so you need to wait for 1s
=> fix sealer alpha mount bug

docs/api/cloudrootfs.md
=> Add introduction for rootfs.

README.md
Signed-off-by: frank-zsy [syzhao1988@126.com](mailto:syzhao1988@126.com)
Add contribution leaderboard badge to README
NONE
=> [Doc] Add contribution leaderboard badge to README

pkg/cluster-runtime/installer.go
=> Plugin phase: post-init-host should before post-install-cluster

.github/workflows/e2e-test-apply.yml, .github/workflows/e2e-test-run.yml, test/e2e_test.go, test/sealer_apply_test.go, test/sealer_build_test.go, test/sealer_images_test.go, test/sealer_login_test.go, test/sealer_run_test.go, test/suites/apply/apply.go, test/suites/image/image.go, test/suites/registry/registry.go, test/testhelper/client/k8s/client.go, test/testhelper/helper.go, test/testhelper/utils.go
After this PR, if e2e test failed, we can view the failed pod log, which is very helpful for us to debug.
for example:
#2013
=> use client-go to interact with the cluster in container and optimize code

.github/workflows/e2e-test-apply.yml, .github/workflows/e2e-test-build.yml, .github/workflows/e2e-test-image.yml, .github/workflows/e2e-test-run.yml
fix:CI Error: Resource not accessible by integration
#2030  
add statuses: write permission
=> fix:CI Error: Resource not accessible by integration

.github/workflows/e2e-test-apply.yml, .github/workflows/e2e-test-build.yml, .github/workflows/e2e-test-image.yml, .github/workflows/e2e-test-run.yml
=> fix:CI error

.github/workflows/e2e-test-apply.yml, .github/workflows/e2e-test-build.yml, .github/workflows/e2e-test-image.yml, .github/workflows/e2e-test-run.yml, .github/workflows/go.yml, .github/workflows/gosec.yml, .github/workflows/markdown.yml, .github/workflows/misspell.yml, .github/workflows/release.yml, .github/workflows/unit-test.yml
update checkout and setup-go actions.
we can find some warning in workflow annotations like: 
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. 
For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
```
actions/checkout@v2 => actions/checkout@v3
actions/setup-go@v2 => actions/setup-go@v3
```
=> chore: update checkout and setup-go actions

pkg/imageengine/buildah/build.go
=> bugfix: multi arch build get wrong arch

utils/ssh/scp.go
=> bugfix: add rw lock to scp progress bar

build/buildimage/differ.go, build/layerutils/manifests/manifests.go, cmd/sealer/cmd/image/build.go, pkg/define/options/options.go
support sealer build --ignored-image-list ignoredlist args
example:
sealer build -f Kubefile -t docker.io/sealerio/kubernetes:v1.22.15 --ignored-image-list ignoredlist
Fixes [#1994](https://github.com/sealerio/sealer/issues/1994)
Fixes #2007
Fixes #1913
Fixes #1553
Fixes #2001
=> support --ignored-image-list ignoredlist args

build/kubefile/parser/kubefile.go
=> feature: inhert APPCMDS

build/kubefile/parser/image_engine_test.go, cmd/sealer/cmd/alpha/manifest.go, cmd/sealer/cmd/image/build.go, pkg/imageengine/buildah/load.go, pkg/imageengine/buildah/manifest.go, pkg/imageengine/interface.go
=> refactor: make image engine manifest resource codes more readable

cmd/sealer/cmd/cluster/run.go, pkg/application/interface.go, pkg/application/v2app.go, types/api/v2/application_types.go
Proposal see: https://github.com/sealerio/sealer/issues/1969
```yaml
kind: Cluster
metadata:
spec:
hosts:
- ips:
- 172.16.26.162
roles:
- master
ssh: {}
image: abc:v1
ssh:
passwd: xxxxxx
port: "22"
user: root
status: {}
---
kind: Application
metadata:
name: my-apps
spec:
launchApps:
- nginx
- yamlapp
- mixedapp
configs:
- name: yamlapp
files:
- path: abc.yaml
strategy: "overwrite"
data: |
i am raw test1
i am raw test2
- path: merge.yaml
strategy: "merge"
data: |
data:
test-key: test-key
metadata:
namespace: test-namespace     
- name: mixedapp
files:
- path: rediscert
strategy: "overwrite"
data: |
redis-user: root
redis-passwd: xxx
```
```shell
[root@iZbp1chh98quny8r8r71bhZ]# …
```
=> feat:support modify app files via Clusterfile

pkg/clusterfile/decoder.go
=> chore: expose the decode cluster interface to public

cmd/sealer/cmd/cluster/cluster.go, cmd/sealer/cmd/cluster/run.go, cmd/sealer/cmd/cluster/upgrade.go, cmd/sealer/cmd/types/types.go, common/common.go, pkg/clusterfile/clusterfile.go
change upgrade mode to cmd, support upgrade with cluster file
=> add upgrade cmd

cmd/sealer/cmd/cluster/apply.go, cmd/sealer/cmd/cluster/run.go, cmd/sealer/cmd/cluster/upgrade.go, cmd/sealer/cmd/utils/application.go, cmd/sealer/cmd/utils/application_test.go, pkg/clusterfile/decoder.go, types/api/v2/application_types.go
1. move `ConstructApplication` to utils
2. add decode check for application
=> add decode check for application

test/sealer_build_test.go, test/suites/build/build.go
=> fix e2e build test

cmd/sealer/cmd/alpha/host-alias.go, pkg/clusterfile/clusterfile.go
=> Fix set host alias not save new hostalias info into clusterfile.

pkg/imageengine/buildah/load.go, pkg/imageengine/buildah/save.go
=> bugfix: return err when load image instance failed

test/sealer_images_test.go
delete mount e2e test
unable to read, write and mount files due to insufficient container permissions.
I have recorded this problem, and I will try to solve it later.
=> delete mount e2e test

.github/workflows/e2e-test-apply.yml, .github/workflows/e2e-test-build.yml, .github/workflows/e2e-test-image.yml, .github/workflows/e2e-test-run.yml, .github/workflows/unit-test.yml, CONTRIBUTING.md, test/suites/build/build.go, test/suites/image/mount.go
add e2e coverage and run e2e when pull request : after pull request will trigger e2e and we can see unitest coverage and e2e-test coverage,like:
=> chore: add e2e coverage and run e2e when pull request

pkg/clusterfile/decoder.go
=> Fix cidr multi format.

cmd/sealer/cmd/cluster/upgrade.go
=> bugfix: use clusterfile file to do upgrade

common/common.go, pkg/runtime/kubernetes/init.go, pkg/runtime/kubernetes/join_masters.go, pkg/runtime/kubernetes/join_nodes.go, pkg/runtime/kubernetes/utils.go
=> Support set node name as node ip using env UseIPasNodeName.

pkg/application/v2app.go
=> bugfix : write image extension to disk

cmd/sealer/cmd/cluster/cluster.go, cmd/sealer/cmd/cluster/rollback.go, cmd/sealer/cmd/types/types.go, pkg/cluster-runtime/hook.go, pkg/cluster-runtime/rollback.go
=> add sealer rollback

cmd/sealer/cmd/alpha/mount.go, cmd/sealer/cmd/alpha/umount.go
=> optimization mount list

Makefile
Makefiles cross-compile arm
Fixes #2050 use local go env to build sealer binary
```bash
❯ ls ./_output/bin/sealer/linux_arm64/sealer -al
-rwxr-xr-x 1 root root 52035584 Mar 28 14:05 ./_output/bin/sealer/linux_arm64/sealer
```
no
=> feature(makefile): Makefiles cross-compile arm

cmd/sealer/cmd/cluster/rollback.go, cmd/sealer/cmd/cluster/upgrade.go
=> Fix image name will be empty when use multi arch local image.

utils/progressbar/progressbar.go
=> fix: The progress bar is complete, but the actual file copy is still being done

ROADMAP.md
=> chore: update roadmap doc

pkg/cluster-runtime/installer.go, pkg/infradriver/ssh_infradriver.go, pkg/infradriver/utils.go, pkg/infradriver/utils_test.go
#2163 
support delete taint
```shell
[root@iZj6c8gb4krnxlhlzkv8ygZ ~]# cat .sealer/Clusterfile
kind: Cluster
metadata:
spec:
containerRuntime: {}
env:
- LocalRegistryDomain=sea.hub
- LocalRegistryPort=5000
- LocalRegistryURL=sea.hub:5000
- RegistryDomain=sea.hub
- RegistryPort=5000
- RegistryURL=sea.hub:5000
hosts:
- ips:
- 172.16.130.22
roles:
- master
ssh: {}
taints:
image: docker.io/sealerio/kubernetes:v1-22-15-sealerio-2
registry:
localRegistry:
cert: {}
domain: sea.hub
ha: true
insecure: false
port: 5000
ssh:
passwd: Seadent123
port: "22"
user: root
status: {}
```
=> support delete taint

cmd/sealer/cmd/cluster/apply.go, cmd/sealer/cmd/cluster/delete.go, cmd/sealer/cmd/cluster/join.go, cmd/sealer/cmd/cluster/rollback.go, cmd/sealer/cmd/cluster/run.go, cmd/sealer/cmd/cluster/scale-up.go, cmd/sealer/cmd/cluster/upgrade.go, cmd/sealer/cmd/types/types.go, pkg/imagedistributor/interface.go, pkg/imagedistributor/mount.go, pkg/imagedistributor/options.go, pkg/imagedistributor/scp_distributor.go
add flag  `ignore-cache` for run, apply, join, scale-up, rollback, indicates that whether use cache when distribute sealer image, default is false.
Fixes #2010
=> feat: support cache sealer image

README.md
=> optimization readme doc

build/kubefile/command/command.go, build/kubefile/parser/kubefile.go, build/kubefile/parser/parse.go, build/kubefile/parser/parse_test.go, cmd/sealer/cmd/image/build.go, pkg/define/application/v1/application.go, pkg/define/application/version/version.go, pkg/define/image/v1/sealer_image.go
Kubefile:
```shell
FROM scratch
ENV globalKey=globalValue
APP app1 local://app1
APP app2 local://app2
APP app3 local://app3
APPENV app1 key1=value1 key2=value2
LAUNCH ["app1","app2"]
```
```json
{
"buildClient": {
"sealerVersion": "unknown",
"buildahVersion": "1.27.1"
},
"schemaVersion": "v1alpha1",
"type": "app-installer",
"applications": [
{
"name": "app1",
"type": "shell",
"envs": [
"key1=value1",
"key2=value2",
],
"files": [
"app1.sh"
],
"version": "v1"
},
{
"name": "app2",
"type": "shell",
"files": [
"app2.sh"
],
"version": "v1"
},
{
"name": "app3",
"type": "shell",
"files": [
"app3.sh"
],
"version": "v1"
}
],
"labels": {
"io.buildah.version": "1.27.1",
"io.sealer.version": "unknown"
},
"env": {
"globalKey": "globalValue"
},
"launch": {
"app_names": [
"app1",
"app2"
]
}
}
```
Fixes …
=> feat:support env and appenv instruction

MAINTAINERS.md
@Starnop has made outstanding contributions to sealer. He mainly made the following contributions：
Responsible for 3 versions of R&D management
Responsible for the refactoring and development of new application modules
Organize community meetings and events
He is still willing to contribute more to the maintenance of the community and the future development.
With the trust @Starnop  built in the community, I proposed to add him as a maintainer in sealer project.
Also cc @kakaZhou719
=> Nominate Yuxing Liu as a maintainer.

MAINTAINERS.md
=> rename kakazhou email address

.github/workflows/e2e-test-apply.yml
=> use pr head sha value to checkout code

.github/workflows/e2e-test-apply.yml, .github/workflows/e2e-test-build.yml, .github/workflows/e2e-test-image.yml, .github/workflows/e2e-test-run.yml
=> use pr head sha  value to checkout code

.github/workflows/release.yml
=> Support binary upload to oss

cmd/sealer/cmd/cluster/delete.go, cmd/sealer/cmd/utils/cluster.go
1. bugfix: return error if scale ip already in cluster
2. optimize the delete prompt
=> bugfix: return error if scale ip already in cluster

build/kubefile/parser/kubefile.go, cmd/sealer/cmd/cluster/installer.go, cmd/sealer/cmd/cluster/rollback.go, cmd/sealer/cmd/cluster/upgrade.go, cmd/sealer/cmd/image/build.go, pkg/application/appdriver.go, pkg/application/appdriver_test.go, pkg/define/application/v1/application.go, pkg/define/application/version/version.go, pkg/define/image/v1/sealer_image.go, test/testhelper/client/k8s/client.go, types/api/v2/application_types.go
1. set appcmds value to imageExtension.application 
2. refactor new app driver code, format it firstly and use application spec to override it.
3. add some UT test
=>  refactor: set appcmds value to application
